import type {
  MemoryInfo,
  MemoryRegion,
  MemoryRegionField,
  MemoryRegionArrayField,
  MemoryRegionSubdividedField,
  BaseOffsettableMemoryRegion,
  Target,
} from '@rawrs/architecture/Target';

import type VirtualMachine from './VirtualMachine';

import {
  ArrayAccessNode,
  AssignmentNode,
  BinaryExpressionNode,
  BinaryLogicNode,
  ChoiceExpressionNode,
  CommentNode,
  ComparisonNode,
  ComparisonEvaluationNode,
  EmptyNode,
  ExpressionNode,
  RepeatIfNode,
  IfBlockNode,
  LocalOperandNode,
  LoopBlockNode,
  LoopIfNode,
  MemoryOperandNode,
  NextIfNode,
  Node,
  OperandNode,
  RaiseExpressionNode,
  RegisterChoiceExpressionNode,
  RegisterOperandNode,
  StatementNode,
  TernaryExpressionNode,
  UnaryExpressionNode,
} from './ast';
import type {
  RegisterReference,
  LocalMap,
  LocalReference,
  LocalsInfo,
  MemoryMap,
  MemoryMapping,
  MemoryReference,
  Reference,
  RegisterMap,
  GeneratorContext,
} from './types';

//const foo: Node[] = [];

/**
 * Takes a syntax tree via a root StatementNode (generated by Parser) and
 * resolves the identifier OperandNode elements within to point to a machine's
 * internal memory map.
 */
class Resolver {
  readonly machine: VirtualMachine;
  readonly locals: LocalsInfo;

  constructor(machine: VirtualMachine, locals: LocalsInfo) {
    this.machine = machine;
    this.locals = locals;
  }

  get target(): Target {
    return this.machine.target;
  }

  get memoryMap(): MemoryMap {
    return this.machine.memoryMap;
  }

  get registerMap(): RegisterMap {
    return this.machine.registerMap;
  }

  /**
   * Returns a copy of the AST with resolved instances of Operands that point to
   * named hardware resources or registers.
   */
  resolve(
    node: StatementNode,
    locals: LocalsInfo,
    localMap: LocalMap,
  ): StatementNode {
    return new StatementNode(
      this.resolveNode(node.node, locals, localMap),
      node.next ? this.resolve(node.next, locals, localMap) : undefined,
    );
  }

  resolveNode<T extends Node = Node>(
    node: T,
    locals: LocalsInfo,
    localMap: LocalMap,
  ): T {
    //foo.push(node);
    let ret: Node = node;
    if (node instanceof CommentNode) {
      ret = node;
    } else if (node instanceof AssignmentNode) {
      ret = new AssignmentNode(
        this.resolveNode(node.destination, locals, localMap) as OperandNode,
        this.resolveNode(
          node.expression,
          locals,
          localMap,
        ) as unknown as ExpressionNode,
      );
    } else if (node instanceof BinaryLogicNode) {
      ret = new BinaryLogicNode(
        this.resolveNode(
          node.operand,
          locals,
          localMap,
        ) as unknown as ComparisonNode,
        node.operator,
        this.resolveNode(node.argument, locals, localMap),
      );
    } else if (node instanceof ComparisonEvaluationNode) {
      ret = new ComparisonEvaluationNode(
        this.resolveNode(
          node.operand,
          locals,
          localMap,
        ) as unknown as ComparisonNode,
        node.operator,
        this.resolveNode(
          node.argument,
          locals,
          localMap,
        ) as unknown as ComparisonNode,
      );
    } else if (node instanceof UnaryExpressionNode) {
      ret = new UnaryExpressionNode(
        this.resolveNode(
          node.operand,
          locals,
          localMap,
        ) as unknown as ExpressionNode,
        node.operator,
      );
    } else if (node instanceof BinaryExpressionNode) {
      const operand = this.resolveNode(node.operand, locals, localMap);
      const argument = this.resolveNode(node.argument, locals, localMap);

      // Perform constant value operation
      if (
        operand instanceof OperandNode &&
        typeof operand.value === 'number' &&
        argument instanceof OperandNode &&
        typeof argument.value === 'number'
      ) {
        const value =
          node.operator === '|' ? operand.value | argument.value : 0;
        ret = new OperandNode(value);
      } else if (
        operand instanceof OperandNode &&
        typeof operand.value === 'number' &&
        ((operand.value === 0 && ['+', '|'].includes(node.operator)) ||
          (operand.value === 1 && node.operator === '*'))
      ) {
        // No-op (0 + ...) (... | 0) (1 * ...)
        ret = argument;
      } else if (
        argument instanceof OperandNode &&
        typeof argument.value === 'number' &&
        ((argument.value === 0 && ['+', '|'].includes(node.operator)) ||
          (argument.value === 1 && node.operator === '*'))
      ) {
        // No-op (... + 0) (... | 0) (... * 1)
        ret = operand;
      } else if (
        operand instanceof OperandNode &&
        typeof operand.value === 'number' &&
        operand.value === 0 &&
        node.operator === '*'
      ) {
        // No-op (0 * ...)
        ret = new OperandNode(0);
      } else if (
        argument instanceof OperandNode &&
        typeof argument.value === 'number' &&
        argument.value === 0 &&
        node.operator === '*'
      ) {
        // No-op (... * 0)
        ret = new OperandNode(0);
      } else {
        ret = new BinaryExpressionNode(
          operand as unknown as ExpressionNode,
          node.operator,
          argument as unknown as ExpressionNode,
        );
      }
    } else if (node instanceof TernaryExpressionNode) {
      ret = new TernaryExpressionNode(
        this.resolveNode(node.condition, locals, localMap),
        this.resolveNode(
          node.operand,
          locals,
          localMap,
        ) as unknown as ExpressionNode,
        this.resolveNode(node.whenFalse, locals, localMap),
      );
    } else if (node instanceof RaiseExpressionNode) {
      ret = new RaiseExpressionNode(
        this.resolveOperand(
          node.operand as OperandNode,
          locals,
          localMap,
          node.operand.coercion,
          true,
        ),
        node.condition
          ? this.resolveNode(node.condition, locals, localMap)
          : undefined,
      );
    } else if (node instanceof IfBlockNode) {
      ret = new IfBlockNode(
        this.resolveNode(node.condition, locals, localMap),
        node.body ? this.resolve(node.body, locals, localMap) : undefined,
      );
    } else if (node instanceof LoopBlockNode) {
      ret = new LoopBlockNode(
        node.name,
        this.resolveNode(node.condition, locals, localMap) as unknown as
          | LoopIfNode
          | RepeatIfNode,
        node.body ? this.resolve(node.body, locals, localMap) : undefined,
      );
    } else if (node instanceof LoopIfNode) {
      ret = new LoopIfNode(this.resolveNode(node.condition, locals, localMap));
    } else if (node instanceof RepeatIfNode) {
      ret = new RepeatIfNode(
        this.resolveNode(node.condition, locals, localMap),
      );
    } else if (node instanceof NextIfNode) {
      ret = new NextIfNode(this.resolveNode(node.condition, locals, localMap));
    } else if (node instanceof ChoiceExpressionNode) {
      ret = this.resolveChoice(node, locals, localMap);
    } else if (node instanceof ComparisonNode) {
      ret = new ComparisonNode(
        this.resolveNode(node.operand, locals, localMap),
      );
    } else if (node instanceof ExpressionNode) {
      // Collapse single item expressions
      if (node.operand instanceof OperandNode) {
        return this.resolveNode(node.operand, locals, localMap) as unknown as T;
      }
      ret = new ExpressionNode(
        this.resolveNode(node.operand, locals, localMap),
      );
    } else if (node instanceof OperandNode) {
      ret = this.resolveOperand(node, locals, localMap);
    } else if (node instanceof EmptyNode) {
      ret = node;
    } else {
      throw new Error(`Unknown syntax node discovered.`);
    }

    //foo.pop();
    return ret as unknown as T;
  }

  resolveChoice(
    node: ChoiceExpressionNode,
    locals: LocalsInfo,
    localMap: LocalMap,
  ): ExpressionNode | RegisterChoiceExpressionNode {
    if (node.index.operand instanceof OperandNode) {
      const operand = node.index.operand as OperandNode;
      if (typeof operand.value === 'number') {
        // We know the index... just emit that choice
        return new ExpressionNode(node.choices[operand.value]);
      }
    }

    const resolved: OperandNode[] = node.choices.map((subNode) =>
      this.resolveOperand(subNode, locals, localMap, node.coercion),
    );

    // All choices must have the same size / operand (or there is a coercion on the whole list)
    // TODO: enforce this rule

    const choices: RegisterOperandNode[] = (
      resolved as RegisterOperandNode[]
    ).filter(
      (subNode) =>
        (subNode as RegisterOperandNode).reference?.type === 'register',
    );
    const coercion = node.coercion;
    const signed: boolean = !!coercion?.startsWith('i');
    const size: number =
      coercion !== undefined
        ? parseInt(coercion.slice(1))
        : choices[0].reference.mapping.size;

    const references: RegisterReference[] = choices.map((choice) => ({
      ...choice.reference,
      size,
      signed,
    }));

    if (resolved.length !== choices.length) {
      throw new Error(`Choices aren't all registers`);
    }

    // Determine an access pattern
    const { pattern, halved, addresses, diff } =
      this.determinePattern(references);

    // Craft the efficient index operation based on the pattern
    const index: ExpressionNode = pattern
      ? new BinaryExpressionNode(
          halved
            ? new BinaryExpressionNode(
                new BinaryExpressionNode(
                  node.index,
                  '&',
                  new ExpressionNode(new OperandNode(addresses.length / 2)),
                ),
                '>>',
                new ExpressionNode(
                  new OperandNode(Math.log2(addresses.length / 2)),
                ),
              )
            : new ExpressionNode(new OperandNode(0)),
          '+',
          new BinaryExpressionNode(
            // The starting address (the addresses are in order for patterns)
            new ExpressionNode(new OperandNode(addresses[0])),
            '+',
            // The 'diff' holds the index factor
            // diff * ...
            new BinaryExpressionNode(
              new ExpressionNode(new OperandNode(diff)),
              '*',
              // When halved, there are two equally-sized patterns
              // (index & ((addresses.length / 2) - 1)) + (addresses[length / 2] - addresses[0]) * ((index & (addresses.length / 2)) >> (addresses.length / 2))
              // For instance, if there are 8 choices that alternate in pairs, we can split the list
              // On x86, we might have the 8-bit access patterns [AL, CL, DL, BL, AH, CH, DH, BH]
              // which are associated with these, potentially, addresses: [0, 2, 4, 6, 1, 3, 5, 7]
              // When halved, we choose [0, 2, 4, 6] and then elect to increment if over the half-way point.
              //
              // So it is `start + diff * (index & 0b11) + ((index & 0b100) >> 2)
              //
              // It it were not halved, we just do math! For x86, the 16-bit access pattern is just
              // [AX, CX, DX, BX, SP, BP, SI, DI] which could be laid out in memory opportunistically
              // such that it is [0, 2, 4, 6, 8, 10, 12, 14]. Therefore, it is just:
              // `start + diff * index` or `0 + 2 * index`.
              //
              // More information is described in the `determinePattern` method.
              halved
                ? new BinaryExpressionNode(
                    node.index,
                    '&',
                    new ExpressionNode(
                      new OperandNode(addresses.length / 2 - 1),
                    ),
                  )
                : node.index,
            ),
          ),
        )
      : // There is no good option to compute the address, so we have to use an
        // actual array of options and do it indirectly.
        new ExpressionNode(new OperandNode(0));

    return new RegisterChoiceExpressionNode(
      choices,
      this.resolveNode(index, locals, localMap),
      coercion,
    );
  }

  resolveOperand(
    node: OperandNode,
    locals: LocalsInfo,
    localMap: LocalMap,
    coercion?: string,
    interrupt?: boolean,
  ): OperandNode {
    if (typeof node.value !== 'string') {
      // This is just a numeric value
      return node;
    }

    // This should reference an interrupt, possibly
    if (interrupt) {
      const interruptInfo = (this.target.interrupts?.vectors || []).find(
        (interruptInfo) => interruptInfo.identifier === node.value,
      );
      if (interruptInfo) {
        return new OperandNode(interruptInfo.index);
      }
    }

    // Get the reference described by this operand
    const reference = this.locateOperand(node, {
      mode: this.target.modes?.[0]?.identifier || 'default',
      locals: {
        ...this.locals,
        ...locals,
      },
      localMap,
    });

    coercion ||= node.coercion;
    const signed = coercion?.startsWith('i');
    const size = coercion ? parseInt(coercion.slice(1)) : 0;

    if (reference.type === 'local') {
      return new LocalOperandNode(reference, node, coercion || node.coercion);
    } else if (reference.type === 'memory') {
      return new MemoryOperandNode(
        reference as unknown as MemoryReference,
        node,
        coercion || node.coercion,
      );
    } else if (reference.type === 'register') {
      return new RegisterOperandNode(
        {
          ...reference,
          size: size || reference.size,
          signed,
        },
        node,
        coercion || node.coercion,
      );
    }

    throw new Error(`Cannot dereference operand ${node.value}`);

    return node;
  }

  /**
   * Attempts to resolve an OperandNode with a register reference.
   */
  locateRegisterOperand(
    operand: OperandNode,
    _context: GeneratorContext,
  ): RegisterReference | undefined {
    if (typeof operand.value !== 'string') {
      throw new Error('Local cannot access a numerical value');
    }

    let ret: RegisterReference | undefined;
    const name: string = operand.value;

    // Determine if this operand refers to a register
    if (name in this.registerMap.registers) {
      ret = {
        type: 'register',
        identifier: name,
        mapping: this.registerMap.registers[name],
        signed: operand.coercion?.startsWith('i'),
        size: operand.coercion
          ? parseInt(operand.coercion.slice(1))
          : this.registerMap.registers[name].size,
      };

      // Handle subfield references
      if (operand.next) {
        if (operand.next instanceof ArrayAccessNode) {
          throw new Error(`Register ${name} cannot be indexed.`);
        }

        const subName = operand.next.value;
        if (typeof subName !== 'string') {
          throw new Error(
            `Register subfield of ${name} cannot be a numerical value.`,
          );
        }

        const tag = `${name}.${subName}`;
        if (tag in this.registerMap.registers) {
          ret = {
            type: 'register',
            identifier: tag,
            mapping: this.registerMap.registers[tag],
            signed: operand.coercion?.startsWith('i'),
            size: operand.coercion
              ? parseInt(operand.coercion.slice(1))
              : this.registerMap.registers[tag].size,
          };
        } else {
          throw new Error(`Register ${tag} is not known.`);
        }
      }
    }

    return ret;
  }

  dereferenceMemoryField(
    operand: OperandNode,
    regionInfo: MemoryRegion | MemoryRegionSubdividedField,
  ): Pick<MemoryReference, 'address' | 'references' | 'size' | 'signed'> {
    let ret: Pick<
      MemoryReference,
      'address' | 'references' | 'size' | 'signed'
    > = {
      address: new ExpressionNode(new OperandNode(0)),
      size: 0,
      signed: false,
    };

    if (typeof operand.value !== 'string') {
      throw new Error(
        'Memory access cannot dereference a numerical value as a field.',
      );
    }

    // Following down into the region will compute the effective address
    const fieldName: string = operand.value;
    const fieldInfo: MemoryRegionField | undefined = regionInfo?.fields?.find(
      (item) => item.identifier === fieldName,
    );

    if (!fieldInfo) {
      throw new Error(
        `Memory access ${regionInfo.identifier} has no field named '${fieldName}'.`,
      );
    }

    if (fieldInfo.offset === undefined) {
      throw new Error(
        `Memory access ${regionInfo.identifier} does not know the dimensions of the field named '${fieldName}'.`,
      );
    }

    ret.references = {
      type: 'memory',
      identifier: fieldInfo.identifier,
      offset: fieldInfo.offset,
      size: fieldInfo.size || 0,
    };

    ret.size = ret.references.size || 0;

    // TODO: handle non-byte aligned accesses
    ret.address = new ExpressionNode(new OperandNode(fieldInfo.offset / 8));

    if (!operand.next) {
      return ret;
    }

    const next: OperandNode | ArrayAccessNode = operand.next;

    // Cell access
    if (next instanceof ArrayAccessNode) {
      const arrayInfo = fieldInfo as MemoryRegionArrayField;
      if (!arrayInfo.count) {
        throw new Error(`Memory access ${fieldName} not indexable.`);
      }

      const cellInfo = arrayInfo.cell;
      if (!cellInfo) {
        throw new Error(`Memory access ${fieldName} has no cell description.`);
      }

      //tag += `[<${cellInfo.identifier}>]`;

      ret.references = {
        type: 'memory',
        identifier: cellInfo.identifier,
        size: fieldInfo.size,
        index: next.index,
      };

      if (next.next) {
        // Further dereferencing
        if (next.next instanceof ArrayAccessNode) {
          // Multi-dimensional cells...
          // TODO: support this
          throw new Error(
            `Memory multi-dimensional array access not permitted.`,
          );
        }

        ret = {
          ...ret,
          ...this.dereferenceMemoryField(next.next, {
            ...cellInfo,
            size: fieldInfo.size,
            offset: 0,
          }),
        };

        ret.address = new BinaryExpressionNode(
          new BinaryExpressionNode(
            next.index,
            '*',
            new ExpressionNode(new OperandNode(fieldInfo.size / 8)),
          ),
          '+',
          ret.address,
        );
      } else {
        ret.address = new BinaryExpressionNode(
          next.index,
          '*',
          new ExpressionNode(new OperandNode(fieldInfo.size / 8)),
        );
      }
    } else {
      // Subfield access
      ret = {
        ...ret,
        ...this.dereferenceMemoryField(next, fieldInfo),
      };
    }

    return ret;
  }

  dereferenceMemoryRegion(
    operand: OperandNode,
    memoryInfo: MemoryInfo,
    mapping: MemoryMapping,
  ): Pick<MemoryReference, 'address' | 'references' | 'size' | 'signed'> {
    const name = memoryInfo.identifier;

    let ret: Pick<
      MemoryReference,
      'address' | 'references' | 'size' | 'signed'
    > = {
      address: new ExpressionNode(new OperandNode(0)),
      size: 0,
      signed: false,
    };

    // We are referencing a region/field/etc
    // The first thing we will find is a region
    if (typeof operand.value !== 'string') {
      throw new Error(
        'Memory access cannot dereference a numerical value as a region name.',
      );
    }

    const regionName = operand.value;
    const regionInfo = memoryInfo.regions?.find(
      (item) => item.identifier === regionName,
    );
    if (!regionInfo) {
      throw new Error(
        `Cannot find memory region ${name}.${regionName} in the target.`,
      );
    }

    // Keep track of the fully qualified reference name.
    const tag = `${name}.${regionInfo.identifier}`;

    // Regions are mapped in the memory map, so we can find an offset there
    // if it is otherwise unknown.
    const regionMapping = this.memoryMap[tag];
    const offset =
      (regionInfo as BaseOffsettableMemoryRegion).offset ||
      (regionMapping.start || mapping.start) - mapping.start;

    if (!operand.next) {
      return ret;
    }

    const next: OperandNode | ArrayAccessNode = operand.next;

    // Array access (direct byte access within the region)
    if (next instanceof ArrayAccessNode) {
      ret.references = {
        type: 'memory',
        identifier: operand.coercion ? `:${operand.coercion}` : ':u8',
        index: next.index,
        size: operand.coercion ? parseInt(operand.coercion.slice(1)) : 8,
        signed: operand.coercion?.startsWith('i'),
      };

      ret.size = ret.references.size;
      ret.signed = ret.references.signed;

      ret.address = new BinaryExpressionNode(
        new ExpressionNode(new OperandNode(offset)),
        '+',
        next.index,
      );

      if (next.next) {
        throw new Error(
          `Memory byte access ${tag}[] cannot be further deferenced`,
        );
      }

      return ret;
    }

    // Otherwise, it is a field access
    ret = {
      ...ret,
      ...this.dereferenceMemoryField(next, regionInfo),
    };

    ret.address = new BinaryExpressionNode(
      new ExpressionNode(new OperandNode(offset)),
      '+',
      ret.address,
    );

    return ret;
  }

  dereferenceMemory(
    operand: OperandNode,
    memoryInfo: MemoryInfo,
    mapping: MemoryMapping,
  ): Pick<MemoryReference, 'address' | 'references' | 'size' | 'signed'> {
    if (typeof operand.value !== 'string') {
      throw new Error('Memory cannot access a numerical value');
    }

    let ret: Pick<
      MemoryReference,
      'address' | 'references' | 'size' | 'signed'
    > = {
      address: new ExpressionNode(new OperandNode(0)),
      size: 0,
      signed: false,
    };

    const name: string = memoryInfo.identifier;
    if (!operand.next) {
      return ret;
    }

    const next: OperandNode | ArrayAccessNode = operand.next;

    // Array access (direct byte access within the memory)
    if (next instanceof ArrayAccessNode) {
      ret.references = {
        type: 'memory',
        identifier: operand.coercion ? `:${operand.coercion}` : ':u8',
        index: next.index,
        size: operand.coercion ? parseInt(operand.coercion.slice(1)) : 8,
        signed: operand.coercion?.startsWith('i'),
      };

      ret.size = ret.references.size;
      ret.signed = ret.references.signed;

      ret.address = new BinaryExpressionNode(
        new ExpressionNode(new OperandNode(mapping.start)),
        '+',
        next.index,
      );

      if (next.next) {
        throw new Error(
          `Memory byte access ${name}[] cannot be further deferenced`,
        );
      }

      return ret;
    }

    ret = {
      ...ret,
      ...this.dereferenceMemoryRegion(next, memoryInfo, mapping),
    };

    ret.address = new BinaryExpressionNode(
      new ExpressionNode(new OperandNode(mapping.start)),
      '+',
      ret.address,
    );

    return ret;
  }

  /**
   * Attempts to resolve an OperandNode with a memory reference.
   */
  locateMemoryOperand(
    operand: OperandNode,
    context: GeneratorContext,
  ): MemoryReference | undefined {
    if (typeof operand.value !== 'string') {
      throw new Error('Local cannot access a numerical value.');
    }

    const name: string = operand.value;

    // Determine if this operand refers to a memory value
    if (!(name in this.memoryMap)) {
      return;
    }

    const ret: MemoryReference = {
      type: 'memory',
      identifier: name,
      mapping: this.memoryMap[name],
      ...this.dereferenceMemory(
        operand,
        this.memoryMap[name].info as MemoryInfo,
        this.memoryMap[name],
      ),
    };

    ret.address = this.resolveNode(
      ret.address,
      context.locals,
      context.localMap,
    );

    return ret;
  }

  /**
   * Attempts to resolve an OperandNode with a local reference.
   */
  locateLocalOperand(
    operand: OperandNode,
    context: GeneratorContext,
  ): LocalReference | undefined {
    if (typeof operand.value !== 'string') {
      throw new Error('Local cannot access a numerical value');
    }

    let ret: LocalReference | undefined;
    const name: string = operand.value;

    // Determine if this operand refers to a defined local
    if (name in context.locals) {
      const variableCount = Object.keys(context.localMap).length;

      context.localMap[name] ||= {
        identifier: `v_${variableCount}`,
      };

      ret = {
        type: 'local',
        identifier: name,
        mapping: context.localMap[name],
      };
    }

    return ret;
  }

  /**
   * Resolves an OperandNode into a Reference, or throws an error if it cannot
   * understand how.
   */
  locateOperand(operand: OperandNode, context: GeneratorContext): Reference {
    if (typeof operand.value !== 'string') {
      throw new Error('Local cannot access a numerical value');
    }

    const ret: Reference | undefined =
      this.locateRegisterOperand(operand, context) ||
      this.locateMemoryOperand(operand, context) ||
      this.locateLocalOperand(operand, context);

    if (ret === undefined) {
      console.log(operand);
      throw new Error(`Local ${operand.value} cannot be found.`);
    }

    return ret;
  }

  determinePattern(entries: RegisterReference[]): {
    pattern: boolean;
    halved: boolean;
    addresses: number[];
    memsize: number;
    diff: number;
  } {
    // [a,b,c,d,e,f,g,h][reg]
    // mem[4 * reg]

    // Get address and memory info for each entry
    // They must all be the same size, offset, and length
    let memsize = 0;
    let offset = 0;
    let length = 0;
    const addresses: number[] = entries
      .map((reference) => {
        const {
          size: item_memsize,
          index: item_index,
          offset: item_offset,
          length: item_length,
        } = reference.mapping;
        if (memsize === 0) {
          memsize = item_memsize || 0;
        } else if (item_memsize !== memsize) {
          throw new Error(
            'Error: [...][] index interpolation has misaligned items.',
          );
        }

        if (offset === 0) {
          offset = item_offset || 0;
        } else if (item_offset !== offset) {
          throw new Error(
            'Error: [...][] index interpolation items are of different subfields.',
          );
        }

        if (length === 0) {
          length = item_length || 0;
        } else if (item_length !== length) {
          throw new Error(
            'Error: [...][] index interpolation has resulting registers of different sizes.',
          );
        }

        return item_index;
      })
      .filter((item) => item !== undefined);

    // Let's see if there is a pattern and use that instead
    const diff = addresses[1] - addresses[0];
    let pattern = true;
    for (let i = 1; i < addresses.length - 1; i++) {
      if (addresses[i + 1] - addresses[i] !== diff) {
        pattern = false;
        break;
      }
    }

    // If there is a pattern, then great! This means we just do:
    // addresses[0] + diff * index

    // Try taking an index bit away and seeing if two subarrays have equal differences
    // [0, 2, 4, 6, 1, 3, 5, 7] should show a pattern which can be satisfied by:
    // (i & 0x4) + ((i & 0x3) * 2) when we take away the 3rd bit (i - 0b100)
    let halved = false;
    if (!pattern) {
      // Try taking top or bottom bit away, if we can. We can do that if the number
      // of items is a power of 2. If that is true, we can divide the list into two
      // lists and see if we can mask the top or bottom bit.
      if (Number.isInteger(Math.log2(addresses.length))) {
        // First see if the first half of the array has a pattern... this must be
        // true regardless of taking that bit away.
        const half = addresses.length / 2;
        pattern = true;
        for (let i = 1; i < half - 1; i++) {
          if (addresses[i + 1] - addresses[i] !== diff) {
            pattern = false;
            break;
          }
        }

        if (pattern) {
          // Take the top bit away and check the top array
          for (let i = half + 1; i < addresses.length - 1; i++) {
            if (addresses[i + 1] - addresses[i] !== diff) {
              pattern = false;
              break;
            }
          }

          if (pattern) {
            // Both subarrays have the same difference... so we just add the
            // difference between the addresses[0] and addresses[half] when
            // the index has the first bit... the following is assuming the
            // 'half' is 4:
            //
            // (addresses[0] * diff * (index & 0x3)) +
            //   ((addresses[half] - addresses[0]) * ((index & 0x4) >> 2))
            halved = true;
          }
        }
      }
    }

    if (!pattern) {
      // Oh my, there is a complicated pattern, perhaps
      // Are we looking for just two different values?
      // For instance, x86's [BX,BX,BP,BP,don't care, don't care, BP,BX] pattern
      // has just two options. We can decide if it is BX by shifting the index as
      // though it was repeating and deciding if it is inclusively within 7 to 9.
      // That's quite tricky! Annoying they did it this way.
      //
      // To compute this, you can use something like:
      // addrof(BX) + (addrof(BP) - addrof(BX)) * ((i + 1) & 7) + 5) >> 3
    }

    return {
      pattern,
      halved,
      addresses,
      memsize,
      diff,
    };
  }
}

export default Resolver;
