packages:
  - 'core'
  - 'file-systems'
  - 'virtual-machine'
  - 'processors'
  - 'devices'
  - 'simulators'
  - 'compilers'
  - 'assemblers'
  - 'disassemblers'
  - 'formats'
onlyBuiltDependencies:
  - 'esbuild'
