import type {
  Target,
  OpcodeMatcher,
  OpcodeMatcherField,
  InstructionForm,
} from '@machinery/core';

export interface EncoderFormEntry {
  mnemonic: string;
  operands: string[];
  operandSize?: number;
  opcodeEntries: OpcodeEntry[];
  aliases?: string[];
}

export type OpcodeEntry =
  | { kind: 'fixed'; value: number }
  | { kind: 'ref'; identifier: string }
  | { kind: 'inline'; matcher: OpcodeMatcher };

export class EncoderGenerator {
  constructor(private target: Target) {}

  generate(): string {
    const lines: string[] = [];

    lines.push(`// Generated encoding tables for ${this.target.name}`);
    lines.push(`// Do not edit - generated by machinery-asm`);
    lines.push(``);
    lines.push(`export interface EncoderField {`);
    lines.push(`  identifier: string;`);
    lines.push(`  offset: number;`);
    lines.push(`  size: number;`);
    lines.push(`  signed?: boolean;`);
    lines.push(`  match?: number;`);
    lines.push(`  type?: number;`);
    lines.push(`  encoding?: (string | null)[];`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export interface EncoderMatcher {`);
    lines.push(`  identifier: string;`);
    lines.push(`  name?: string;`);
    lines.push(`  type: number;`);
    lines.push(`  size: number;`);
    lines.push(`  signed?: boolean;`);
    lines.push(`  fields?: EncoderField[];`);
    lines.push(`}`);
    lines.push(``);
    lines.push(`export type OpcodeEntry =`);
    lines.push(`  | { kind: 'fixed'; value: number }`);
    lines.push(`  | { kind: 'ref'; identifier: string }`);
    lines.push(`  | { kind: 'inline'; matcher: EncoderMatcher };`);
    lines.push(``);
    lines.push(`export interface EncoderForm {`);
    lines.push(`  mnemonic: string;`);
    lines.push(`  operands: string[];`);
    lines.push(`  operandSize?: number;`);
    lines.push(`  opcodeEntries: OpcodeEntry[];`);
    lines.push(`  aliases?: string[];`);
    lines.push(`  commutative?: boolean;`);
    lines.push(`  distance?: 'short' | 'near' | 'far';`);
    lines.push(`  addressing?: 'relative' | 'absolute';`);
    lines.push(`  encodingPriority?: number;`);
    lines.push(`}`);
    lines.push(``);

    // Emit the operand definitions lookup
    lines.push(
      `export const operandDefinitions: Record<string, EncoderMatcher> = {`,
    );
    for (const op of this.target.operands) {
      lines.push(
        `  ${JSON.stringify(op.identifier)}: ${this.serializeMatcher(op)},`,
      );
    }
    lines.push(`};`);
    lines.push(``);

    // Emit segment override prefix map
    const segmentPrefixes = this.collectSegmentOverridePrefixes();
    lines.push(
      `export const segmentOverridePrefixes: Record<string, number[]> = {`,
    );
    for (const [name, bytes] of [...segmentPrefixes.entries()].sort(
      ([a], [b]) => a.localeCompare(b),
    )) {
      lines.push(`  ${JSON.stringify(name)}: ${JSON.stringify(bytes)},`);
    }
    lines.push(`};`);
    lines.push(``);

    // Emit prefix byte mappings for REP/REPE/REPNE/LOCK etc.
    lines.push(`export const prefixBytes: Record<string, number> = {`);
    for (const inst of this.target.instructions) {
      if (!inst.prefix) continue;
      if (inst.forms.some((f) => f.segmentOverride)) {
        // Segment overrides: emit each segment name with its opcode byte
        for (const form of inst.forms) {
          if (!form.segmentOverride) continue;
          const opcode =
            typeof form.opcode[0] === 'number' ? form.opcode[0] : 0;
          lines.push(`  ${JSON.stringify(form.segmentOverride)}: ${opcode},`);
        }
        continue;
      }
      const opcode =
        typeof inst.forms[0]?.opcode[0] === 'number'
          ? inst.forms[0].opcode[0]
          : 0;
      const names = [
        inst.identifier.toUpperCase(),
        ...(inst.aliases || []).map((a) => a.toUpperCase()),
      ];
      for (const name of names) {
        lines.push(`  ${JSON.stringify(name)}: ${opcode},`);
      }
    }
    lines.push(`};`);
    lines.push(``);

    // Emit endianness
    lines.push(
      `export const endianness: 'little' | 'big' = ${JSON.stringify(this.target.endianness || 'little')};`,
    );
    lines.push(``);

    // Emit alignment fill byte
    lines.push(
      `export const alignmentFill: number = ${this.target.alignmentFill ?? 0x00};`,
    );
    lines.push(``);

    // Emit the instruction forms
    lines.push(`export const encoderForms: EncoderForm[] = [`);
    for (const inst of this.target.instructions) {
      if (inst.prefix) continue;
      for (const form of inst.forms) {
        if (!form.operands) continue;

        // Build mnemonic list from instruction-level and form-level aliases
        const mnemonics = [inst.identifier.toUpperCase()];
        if (inst.aliases) {
          for (const alias of inst.aliases) {
            mnemonics.push(alias.toUpperCase());
          }
        }
        const formAliases = form.aliases
          ? form.aliases.map((a) => a.toUpperCase())
          : [];
        const allMnemonics = [...mnemonics, ...formAliases];

        // For far forms of return instructions, add a FAR-suffixed mnemonic alias
        if (form.distance === 'far') {
          const farName = inst.identifier.toUpperCase() + 'F';
          if (!allMnemonics.includes(farName)) allMnemonics.push(farName);
        }

        const primary = allMnemonics[0];
        const aliases = allMnemonics.slice(1);

        const entries = this.serializeOpcodeEntries(form);
        lines.push(`  {`);
        lines.push(`    mnemonic: ${JSON.stringify(primary)},`);
        lines.push(`    operands: ${JSON.stringify(form.operands)},`);
        if (form.operandSize !== undefined) {
          lines.push(`    operandSize: ${form.operandSize},`);
        }
        lines.push(`    opcodeEntries: ${entries},`);
        if (aliases.length > 0) {
          lines.push(`    aliases: ${JSON.stringify(aliases)},`);
        }
        if (inst.commutative) {
          lines.push(`    commutative: true,`);
        }
        if (form.distance) {
          lines.push(`    distance: ${JSON.stringify(form.distance)},`);
        }
        if (form.addressing) {
          lines.push(`    addressing: ${JSON.stringify(form.addressing)},`);
        }
        if (form.encodingPriority !== undefined) {
          lines.push(`    encodingPriority: ${form.encodingPriority},`);
        }
        lines.push(`  },`);
      }
    }
    lines.push(`];`);
    lines.push(``);

    return lines.join('\n');
  }

  private collectSegmentOverridePrefixes(): Map<string, number[]> {
    const result = new Map<string, number[]>();
    for (const inst of this.target.instructions) {
      if (!inst.prefix) continue;
      for (const form of inst.forms) {
        if (!form.segmentOverride) continue;
        // Extract fixed opcode bytes for this prefix form
        const bytes: number[] = [];
        for (const entry of form.opcode) {
          if (typeof entry === 'number') {
            bytes.push(entry);
          }
        }
        if (bytes.length > 0) {
          result.set(form.segmentOverride, bytes);
        }
      }
    }
    return result;
  }

  private serializeOpcodeEntries(form: InstructionForm): string {
    const entries: string[] = [];
    for (const entry of form.opcode) {
      if (typeof entry === 'number') {
        entries.push(`{ kind: 'fixed', value: ${entry} }`);
      } else if (typeof entry === 'string') {
        entries.push(`{ kind: 'ref', identifier: ${JSON.stringify(entry)} }`);
      } else {
        entries.push(
          `{ kind: 'inline', matcher: ${this.serializeMatcher(entry as OpcodeMatcher)} }`,
        );
      }
    }
    return `[${entries.join(', ')}]`;
  }

  private serializeMatcher(matcher: OpcodeMatcher): string {
    const parts: string[] = [];
    parts.push(`identifier: ${JSON.stringify(matcher.identifier)}`);
    if (matcher.name) parts.push(`name: ${JSON.stringify(matcher.name)}`);
    parts.push(`type: ${matcher.type}`);
    parts.push(`size: ${matcher.size}`);
    if (matcher.signed) parts.push(`signed: true`);
    if (matcher.fields && matcher.fields.length > 0) {
      const fields = matcher.fields.map((f) => this.serializeField(f));
      parts.push(`fields: [${fields.join(', ')}]`);
    }
    return `{ ${parts.join(', ')} }`;
  }

  private serializeField(field: OpcodeMatcherField): string {
    const parts: string[] = [];
    parts.push(`identifier: ${JSON.stringify(field.identifier)}`);
    parts.push(`offset: ${field.offset}`);
    parts.push(`size: ${field.size}`);
    if (field.signed) parts.push(`signed: true`);
    if (field.match !== undefined) parts.push(`match: ${field.match}`);
    if (field.type !== undefined) parts.push(`type: ${field.type}`);
    if (field.encoding)
      parts.push(`encoding: ${JSON.stringify(field.encoding)}`);
    return `{ ${parts.join(', ')} }`;
  }
}
