import type { Target } from '@machinery/core';
import type { Syntax } from './syntax/Syntax';

export class GrammarGenerator {
  constructor(
    private target: Target,
    private syntax: Syntax,
  ) {}

  generate(): string {
    const lines: string[] = [];

    lines.push(
      `# Generated grammar for ${this.target.name} (${this.syntax.name} syntax)`,
    );
    lines.push(`# Do not edit - generated by machinery-asm`);
    lines.push(``);

    lines.push(this.syntax.generateTokenizer(this.target));
    lines.push(``);
    lines.push(this.syntax.generateGrammarRules(this.target));
    lines.push(``);

    return lines.join('\n');
  }
}
