// Generated encoding tables for Zilog Z80
// Do not edit - generated by machinery-asm

export interface EncoderField {
  identifier: string;
  offset: number;
  size: number;
  signed?: boolean;
  match?: number;
  type?: number;
  encoding?: (string | null)[];
}

export interface EncoderMatcher {
  identifier: string;
  name?: string;
  type: number;
  size: number;
  signed?: boolean;
  fields?: EncoderField[];
}

export type OpcodeEntry =
  | { kind: 'fixed'; value: number }
  | { kind: 'ref'; identifier: string }
  | { kind: 'inline'; matcher: EncoderMatcher };

export interface EncoderForm {
  mnemonic: string;
  operands: string[];
  operandSize?: number;
  opcodeEntries: OpcodeEntry[];
  aliases?: string[];
  commutative?: boolean;
  distance?: 'short' | 'near' | 'far';
  addressing?: 'relative' | 'absolute';
  encodingPriority?: number;
}

export const operandDefinitions: Record<string, EncoderMatcher> = {
  IMM_u8: {
    identifier: 'IMM_u8',
    name: 'Unsigned 8-bit Immediate',
    type: 4,
    size: 8,
    fields: [{ identifier: 'IMM', offset: 0, size: 8 }],
  },
  IMM_i8: {
    identifier: 'IMM_i8',
    name: 'Signed 8-bit Immediate',
    type: 4,
    size: 8,
    signed: true,
    fields: [{ identifier: 'IMM', offset: 0, size: 8, signed: true }],
  },
  IMM_u16: {
    identifier: 'IMM_u16',
    name: 'Unsigned 16-bit Immediate',
    type: 4,
    size: 16,
    fields: [{ identifier: 'IMM', offset: 0, size: 16 }],
  },
  DISP_i8: {
    identifier: 'DISP_i8',
    name: 'Signed 8-bit Displacement',
    type: 2,
    size: 8,
    signed: true,
    fields: [{ identifier: 'DISP', offset: 0, size: 8, signed: true }],
  },
  REL_i8: {
    identifier: 'REL_i8',
    name: 'Relative 8-bit Offset',
    type: 4,
    size: 8,
    signed: true,
    fields: [{ identifier: 'REL', offset: 0, size: 8, signed: true }],
  },
  REG8_SRC: {
    identifier: 'REG8_SRC',
    name: 'Source Register (bits 2-0)',
    type: 1,
    size: 8,
    fields: [
      {
        identifier: 'src',
        offset: 0,
        size: 3,
        type: 1,
        encoding: ['B', 'C', 'D', 'E', 'H', 'L', null, 'A'],
      },
    ],
  },
  REG8_SRC_OR_MEM: {
    identifier: 'REG8_SRC_OR_MEM',
    name: 'Source Register or (HL) (bits 2-0)',
    type: 1,
    size: 8,
    fields: [
      {
        identifier: 'src',
        offset: 0,
        size: 3,
        type: 1,
        encoding: ['B', 'C', 'D', 'E', 'H', 'L', null, 'A'],
      },
    ],
  },
  REG8_DST: {
    identifier: 'REG8_DST',
    name: 'Destination Register (bits 5-3)',
    type: 1,
    size: 8,
    fields: [
      {
        identifier: 'dst',
        offset: 3,
        size: 3,
        type: 1,
        encoding: ['B', 'C', 'D', 'E', 'H', 'L', null, 'A'],
      },
    ],
  },
  REG16_RP: {
    identifier: 'REG16_RP',
    name: 'Register Pair (bits 5-4)',
    type: 1,
    size: 8,
    fields: [
      {
        identifier: 'rp',
        offset: 4,
        size: 2,
        type: 1,
        encoding: ['BC', 'DE', 'HL', 'SP'],
      },
    ],
  },
  REG16_RP2: {
    identifier: 'REG16_RP2',
    name: 'Register Pair for Stack (bits 5-4)',
    type: 1,
    size: 8,
    fields: [
      {
        identifier: 'rp',
        offset: 4,
        size: 2,
        type: 1,
        encoding: ['BC', 'DE', 'HL', 'AF'],
      },
    ],
  },
  RST_VEC: {
    identifier: 'RST_VEC',
    name: 'Restart Vector (bits 5-3)',
    type: 1,
    size: 8,
    fields: [{ identifier: 'vec', offset: 3, size: 3 }],
  },
  BIT_NUM: {
    identifier: 'BIT_NUM',
    name: 'Bit Number (bits 5-3)',
    type: 1,
    size: 8,
    fields: [{ identifier: 'bit', offset: 3, size: 3 }],
  },
  PORT_u8: {
    identifier: 'PORT_u8',
    name: 'Port Address',
    type: 4,
    size: 8,
    fields: [{ identifier: 'PORT', offset: 0, size: 8 }],
  },
};

export const segmentOverridePrefixes: Record<string, number[]> = {};

export const prefixBytes: Record<string, number> = {};

export const endianness: 'little' | 'big' = 'little';

export const alignmentFill: number = 0;

export const encoderForms: EncoderForm[] = [
  {
    mnemonic: 'NOP',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 0 }],
  },
  {
    mnemonic: 'HALT',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 118 }],
  },
  {
    mnemonic: 'DI',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 243 }],
  },
  {
    mnemonic: 'EI',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 251 }],
  },
  {
    mnemonic: 'LD',
    operands: ['B', 'B'],
    opcodeEntries: [{ kind: 'fixed', value: 64 }],
  },
  {
    mnemonic: 'LD',
    operands: ['B', 'C'],
    opcodeEntries: [{ kind: 'fixed', value: 65 }],
  },
  {
    mnemonic: 'LD',
    operands: ['B', 'D'],
    opcodeEntries: [{ kind: 'fixed', value: 66 }],
  },
  {
    mnemonic: 'LD',
    operands: ['B', 'E'],
    opcodeEntries: [{ kind: 'fixed', value: 67 }],
  },
  {
    mnemonic: 'LD',
    operands: ['B', 'H'],
    opcodeEntries: [{ kind: 'fixed', value: 68 }],
  },
  {
    mnemonic: 'LD',
    operands: ['B', 'L'],
    opcodeEntries: [{ kind: 'fixed', value: 69 }],
  },
  {
    mnemonic: 'LD',
    operands: ['B', '(HL)'],
    opcodeEntries: [{ kind: 'fixed', value: 70 }],
  },
  {
    mnemonic: 'LD',
    operands: ['B', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 71 }],
  },
  {
    mnemonic: 'LD',
    operands: ['C', 'B'],
    opcodeEntries: [{ kind: 'fixed', value: 72 }],
  },
  {
    mnemonic: 'LD',
    operands: ['C', 'C'],
    opcodeEntries: [{ kind: 'fixed', value: 73 }],
  },
  {
    mnemonic: 'LD',
    operands: ['C', 'D'],
    opcodeEntries: [{ kind: 'fixed', value: 74 }],
  },
  {
    mnemonic: 'LD',
    operands: ['C', 'E'],
    opcodeEntries: [{ kind: 'fixed', value: 75 }],
  },
  {
    mnemonic: 'LD',
    operands: ['C', 'H'],
    opcodeEntries: [{ kind: 'fixed', value: 76 }],
  },
  {
    mnemonic: 'LD',
    operands: ['C', 'L'],
    opcodeEntries: [{ kind: 'fixed', value: 77 }],
  },
  {
    mnemonic: 'LD',
    operands: ['C', '(HL)'],
    opcodeEntries: [{ kind: 'fixed', value: 78 }],
  },
  {
    mnemonic: 'LD',
    operands: ['C', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 79 }],
  },
  {
    mnemonic: 'LD',
    operands: ['D', 'B'],
    opcodeEntries: [{ kind: 'fixed', value: 80 }],
  },
  {
    mnemonic: 'LD',
    operands: ['D', 'C'],
    opcodeEntries: [{ kind: 'fixed', value: 81 }],
  },
  {
    mnemonic: 'LD',
    operands: ['D', 'D'],
    opcodeEntries: [{ kind: 'fixed', value: 82 }],
  },
  {
    mnemonic: 'LD',
    operands: ['D', 'E'],
    opcodeEntries: [{ kind: 'fixed', value: 83 }],
  },
  {
    mnemonic: 'LD',
    operands: ['D', 'H'],
    opcodeEntries: [{ kind: 'fixed', value: 84 }],
  },
  {
    mnemonic: 'LD',
    operands: ['D', 'L'],
    opcodeEntries: [{ kind: 'fixed', value: 85 }],
  },
  {
    mnemonic: 'LD',
    operands: ['D', '(HL)'],
    opcodeEntries: [{ kind: 'fixed', value: 86 }],
  },
  {
    mnemonic: 'LD',
    operands: ['D', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 87 }],
  },
  {
    mnemonic: 'LD',
    operands: ['E', 'B'],
    opcodeEntries: [{ kind: 'fixed', value: 88 }],
  },
  {
    mnemonic: 'LD',
    operands: ['E', 'C'],
    opcodeEntries: [{ kind: 'fixed', value: 89 }],
  },
  {
    mnemonic: 'LD',
    operands: ['E', 'D'],
    opcodeEntries: [{ kind: 'fixed', value: 90 }],
  },
  {
    mnemonic: 'LD',
    operands: ['E', 'E'],
    opcodeEntries: [{ kind: 'fixed', value: 91 }],
  },
  {
    mnemonic: 'LD',
    operands: ['E', 'H'],
    opcodeEntries: [{ kind: 'fixed', value: 92 }],
  },
  {
    mnemonic: 'LD',
    operands: ['E', 'L'],
    opcodeEntries: [{ kind: 'fixed', value: 93 }],
  },
  {
    mnemonic: 'LD',
    operands: ['E', '(HL)'],
    opcodeEntries: [{ kind: 'fixed', value: 94 }],
  },
  {
    mnemonic: 'LD',
    operands: ['E', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 95 }],
  },
  {
    mnemonic: 'LD',
    operands: ['H', 'B'],
    opcodeEntries: [{ kind: 'fixed', value: 96 }],
  },
  {
    mnemonic: 'LD',
    operands: ['H', 'C'],
    opcodeEntries: [{ kind: 'fixed', value: 97 }],
  },
  {
    mnemonic: 'LD',
    operands: ['H', 'D'],
    opcodeEntries: [{ kind: 'fixed', value: 98 }],
  },
  {
    mnemonic: 'LD',
    operands: ['H', 'E'],
    opcodeEntries: [{ kind: 'fixed', value: 99 }],
  },
  {
    mnemonic: 'LD',
    operands: ['H', 'H'],
    opcodeEntries: [{ kind: 'fixed', value: 100 }],
  },
  {
    mnemonic: 'LD',
    operands: ['H', 'L'],
    opcodeEntries: [{ kind: 'fixed', value: 101 }],
  },
  {
    mnemonic: 'LD',
    operands: ['H', '(HL)'],
    opcodeEntries: [{ kind: 'fixed', value: 102 }],
  },
  {
    mnemonic: 'LD',
    operands: ['H', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 103 }],
  },
  {
    mnemonic: 'LD',
    operands: ['L', 'B'],
    opcodeEntries: [{ kind: 'fixed', value: 104 }],
  },
  {
    mnemonic: 'LD',
    operands: ['L', 'C'],
    opcodeEntries: [{ kind: 'fixed', value: 105 }],
  },
  {
    mnemonic: 'LD',
    operands: ['L', 'D'],
    opcodeEntries: [{ kind: 'fixed', value: 106 }],
  },
  {
    mnemonic: 'LD',
    operands: ['L', 'E'],
    opcodeEntries: [{ kind: 'fixed', value: 107 }],
  },
  {
    mnemonic: 'LD',
    operands: ['L', 'H'],
    opcodeEntries: [{ kind: 'fixed', value: 108 }],
  },
  {
    mnemonic: 'LD',
    operands: ['L', 'L'],
    opcodeEntries: [{ kind: 'fixed', value: 109 }],
  },
  {
    mnemonic: 'LD',
    operands: ['L', '(HL)'],
    opcodeEntries: [{ kind: 'fixed', value: 110 }],
  },
  {
    mnemonic: 'LD',
    operands: ['L', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 111 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(HL)', 'B'],
    opcodeEntries: [{ kind: 'fixed', value: 112 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(HL)', 'C'],
    opcodeEntries: [{ kind: 'fixed', value: 113 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(HL)', 'D'],
    opcodeEntries: [{ kind: 'fixed', value: 114 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(HL)', 'E'],
    opcodeEntries: [{ kind: 'fixed', value: 115 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(HL)', 'H'],
    opcodeEntries: [{ kind: 'fixed', value: 116 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(HL)', 'L'],
    opcodeEntries: [{ kind: 'fixed', value: 117 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(HL)', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 119 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'B'],
    opcodeEntries: [{ kind: 'fixed', value: 120 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'C'],
    opcodeEntries: [{ kind: 'fixed', value: 121 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'D'],
    opcodeEntries: [{ kind: 'fixed', value: 122 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'E'],
    opcodeEntries: [{ kind: 'fixed', value: 123 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'H'],
    opcodeEntries: [{ kind: 'fixed', value: 124 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'L'],
    opcodeEntries: [{ kind: 'fixed', value: 125 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', '(HL)'],
    opcodeEntries: [{ kind: 'fixed', value: 126 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 127 }],
  },
  {
    mnemonic: 'LD',
    operands: ['B', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 6 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['C', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 14 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['D', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 22 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['E', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 30 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['H', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 38 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['L', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 46 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['(HL)', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 54 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 62 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['BC', 'imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 1 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['DE', 'imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 17 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['HL', 'imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 33 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['SP', 'imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 49 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['(BC)', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 2 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(DE)', 'A'],
    opcodeEntries: [{ kind: 'fixed', value: 18 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', '(BC)'],
    opcodeEntries: [{ kind: 'fixed', value: 10 }],
  },
  {
    mnemonic: 'LD',
    operands: ['A', '(DE)'],
    opcodeEntries: [{ kind: 'fixed', value: 26 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(imm)', 'HL'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 34 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['HL', '(imm)'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 42 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['(imm)', 'A'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 50 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['A', '(imm)'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 58 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['SP', 'HL'],
    opcodeEntries: [{ kind: 'fixed', value: 249 }],
  },
  {
    mnemonic: 'LD',
    operands: ['(imm)', 'BC'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 67 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['BC', '(imm)'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 75 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['(imm)', 'DE'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 83 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['DE', '(imm)'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 91 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['(imm)', 'HL'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 99 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['HL', '(imm)'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 107 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['(imm)', 'SP'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 115 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['SP', '(imm)'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 123 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['I', 'A'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 71 },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['R', 'A'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 79 },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'I'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 87 },
    ],
  },
  {
    mnemonic: 'LD',
    operands: ['A', 'R'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 95 },
    ],
  },
  {
    mnemonic: 'ADD',
    operands: ['A', 'B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 128 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['A', 'C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 129 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['A', 'D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 130 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['A', 'E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 131 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['A', 'H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 132 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['A', 'L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 133 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['A', '(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 134 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['A', 'A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 135 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['A', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 198 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'ADD',
    operands: ['HL', 'BC'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 9 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['HL', 'DE'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 25 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['HL', 'HL'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 41 }],
  },
  {
    mnemonic: 'ADD',
    operands: ['HL', 'SP'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 57 }],
  },
  {
    mnemonic: 'ADC',
    operands: ['A', 'B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 136 }],
  },
  {
    mnemonic: 'ADC',
    operands: ['A', 'C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 137 }],
  },
  {
    mnemonic: 'ADC',
    operands: ['A', 'D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 138 }],
  },
  {
    mnemonic: 'ADC',
    operands: ['A', 'E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 139 }],
  },
  {
    mnemonic: 'ADC',
    operands: ['A', 'H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 140 }],
  },
  {
    mnemonic: 'ADC',
    operands: ['A', 'L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 141 }],
  },
  {
    mnemonic: 'ADC',
    operands: ['A', '(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 142 }],
  },
  {
    mnemonic: 'ADC',
    operands: ['A', 'A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 143 }],
  },
  {
    mnemonic: 'ADC',
    operands: ['A', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 206 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'ADC',
    operands: ['HL', 'BC'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 74 },
    ],
  },
  {
    mnemonic: 'ADC',
    operands: ['HL', 'DE'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 90 },
    ],
  },
  {
    mnemonic: 'ADC',
    operands: ['HL', 'HL'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 106 },
    ],
  },
  {
    mnemonic: 'ADC',
    operands: ['HL', 'SP'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 122 },
    ],
  },
  {
    mnemonic: 'SUB',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 144 }],
  },
  {
    mnemonic: 'SUB',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 145 }],
  },
  {
    mnemonic: 'SUB',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 146 }],
  },
  {
    mnemonic: 'SUB',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 147 }],
  },
  {
    mnemonic: 'SUB',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 148 }],
  },
  {
    mnemonic: 'SUB',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 149 }],
  },
  {
    mnemonic: 'SUB',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 150 }],
  },
  {
    mnemonic: 'SUB',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 151 }],
  },
  {
    mnemonic: 'SUB',
    operands: ['imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 214 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'SBC',
    operands: ['A', 'B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 152 }],
  },
  {
    mnemonic: 'SBC',
    operands: ['A', 'C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 153 }],
  },
  {
    mnemonic: 'SBC',
    operands: ['A', 'D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 154 }],
  },
  {
    mnemonic: 'SBC',
    operands: ['A', 'E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 155 }],
  },
  {
    mnemonic: 'SBC',
    operands: ['A', 'H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 156 }],
  },
  {
    mnemonic: 'SBC',
    operands: ['A', 'L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 157 }],
  },
  {
    mnemonic: 'SBC',
    operands: ['A', '(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 158 }],
  },
  {
    mnemonic: 'SBC',
    operands: ['A', 'A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 159 }],
  },
  {
    mnemonic: 'SBC',
    operands: ['A', 'imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 222 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'SBC',
    operands: ['HL', 'BC'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 66 },
    ],
  },
  {
    mnemonic: 'SBC',
    operands: ['HL', 'DE'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 82 },
    ],
  },
  {
    mnemonic: 'SBC',
    operands: ['HL', 'HL'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 98 },
    ],
  },
  {
    mnemonic: 'SBC',
    operands: ['HL', 'SP'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 114 },
    ],
  },
  {
    mnemonic: 'INC',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 4 }],
  },
  {
    mnemonic: 'INC',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 12 }],
  },
  {
    mnemonic: 'INC',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 20 }],
  },
  {
    mnemonic: 'INC',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 28 }],
  },
  {
    mnemonic: 'INC',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 36 }],
  },
  {
    mnemonic: 'INC',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 44 }],
  },
  {
    mnemonic: 'INC',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 52 }],
  },
  {
    mnemonic: 'INC',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 60 }],
  },
  {
    mnemonic: 'INC',
    operands: ['BC'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 3 }],
  },
  {
    mnemonic: 'INC',
    operands: ['DE'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 19 }],
  },
  {
    mnemonic: 'INC',
    operands: ['HL'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 35 }],
  },
  {
    mnemonic: 'INC',
    operands: ['SP'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 51 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 5 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 13 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 21 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 29 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 37 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 45 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 53 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 61 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['BC'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 11 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['DE'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 27 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['HL'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 43 }],
  },
  {
    mnemonic: 'DEC',
    operands: ['SP'],
    operandSize: 16,
    opcodeEntries: [{ kind: 'fixed', value: 59 }],
  },
  {
    mnemonic: 'AND',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 160 }],
  },
  {
    mnemonic: 'AND',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 161 }],
  },
  {
    mnemonic: 'AND',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 162 }],
  },
  {
    mnemonic: 'AND',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 163 }],
  },
  {
    mnemonic: 'AND',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 164 }],
  },
  {
    mnemonic: 'AND',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 165 }],
  },
  {
    mnemonic: 'AND',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 166 }],
  },
  {
    mnemonic: 'AND',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 167 }],
  },
  {
    mnemonic: 'AND',
    operands: ['imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 230 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'OR',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 176 }],
  },
  {
    mnemonic: 'OR',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 177 }],
  },
  {
    mnemonic: 'OR',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 178 }],
  },
  {
    mnemonic: 'OR',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 179 }],
  },
  {
    mnemonic: 'OR',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 180 }],
  },
  {
    mnemonic: 'OR',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 181 }],
  },
  {
    mnemonic: 'OR',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 182 }],
  },
  {
    mnemonic: 'OR',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 183 }],
  },
  {
    mnemonic: 'OR',
    operands: ['imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 246 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'XOR',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 168 }],
  },
  {
    mnemonic: 'XOR',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 169 }],
  },
  {
    mnemonic: 'XOR',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 170 }],
  },
  {
    mnemonic: 'XOR',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 171 }],
  },
  {
    mnemonic: 'XOR',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 172 }],
  },
  {
    mnemonic: 'XOR',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 173 }],
  },
  {
    mnemonic: 'XOR',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 174 }],
  },
  {
    mnemonic: 'XOR',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 175 }],
  },
  {
    mnemonic: 'XOR',
    operands: ['imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 238 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'CP',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 184 }],
  },
  {
    mnemonic: 'CP',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 185 }],
  },
  {
    mnemonic: 'CP',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 186 }],
  },
  {
    mnemonic: 'CP',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 187 }],
  },
  {
    mnemonic: 'CP',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 188 }],
  },
  {
    mnemonic: 'CP',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 189 }],
  },
  {
    mnemonic: 'CP',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 190 }],
  },
  {
    mnemonic: 'CP',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [{ kind: 'fixed', value: 191 }],
  },
  {
    mnemonic: 'CP',
    operands: ['imm'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 254 },
      { kind: 'ref', identifier: 'IMM_u8' },
    ],
  },
  {
    mnemonic: 'JP',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 195 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JP',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 194 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['JP NZ'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JP',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 202 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['JP Z'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JP',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 210 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['JP NC'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JP',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 218 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['JP C'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JP',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 226 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['JP PO'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JP',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 234 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['JP PE'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JP',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 242 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['JP P'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JP',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 250 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['JP M'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JP',
    operands: ['(HL)'],
    opcodeEntries: [{ kind: 'fixed', value: 233 }],
    addressing: 'absolute',
  },
  {
    mnemonic: 'JR',
    operands: ['rel'],
    opcodeEntries: [
      { kind: 'fixed', value: 24 },
      { kind: 'ref', identifier: 'REL_i8' },
    ],
    distance: 'short',
    addressing: 'relative',
  },
  {
    mnemonic: 'JR',
    operands: ['rel'],
    opcodeEntries: [
      { kind: 'fixed', value: 32 },
      { kind: 'ref', identifier: 'REL_i8' },
    ],
    aliases: ['JR NZ'],
    distance: 'short',
    addressing: 'relative',
  },
  {
    mnemonic: 'JR',
    operands: ['rel'],
    opcodeEntries: [
      { kind: 'fixed', value: 40 },
      { kind: 'ref', identifier: 'REL_i8' },
    ],
    aliases: ['JR Z'],
    distance: 'short',
    addressing: 'relative',
  },
  {
    mnemonic: 'JR',
    operands: ['rel'],
    opcodeEntries: [
      { kind: 'fixed', value: 48 },
      { kind: 'ref', identifier: 'REL_i8' },
    ],
    aliases: ['JR NC'],
    distance: 'short',
    addressing: 'relative',
  },
  {
    mnemonic: 'JR',
    operands: ['rel'],
    opcodeEntries: [
      { kind: 'fixed', value: 56 },
      { kind: 'ref', identifier: 'REL_i8' },
    ],
    aliases: ['JR C'],
    distance: 'short',
    addressing: 'relative',
  },
  {
    mnemonic: 'DJNZ',
    operands: ['rel'],
    opcodeEntries: [
      { kind: 'fixed', value: 16 },
      { kind: 'ref', identifier: 'REL_i8' },
    ],
    distance: 'short',
    addressing: 'relative',
  },
  {
    mnemonic: 'CALL',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 205 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    addressing: 'absolute',
  },
  {
    mnemonic: 'CALL',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 196 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['CALL NZ'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'CALL',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 204 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['CALL Z'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'CALL',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 212 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['CALL NC'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'CALL',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 220 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['CALL C'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'CALL',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 228 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['CALL PO'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'CALL',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 236 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['CALL PE'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'CALL',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 244 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['CALL P'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'CALL',
    operands: ['imm'],
    operandSize: 16,
    opcodeEntries: [
      { kind: 'fixed', value: 252 },
      { kind: 'ref', identifier: 'IMM_u16' },
    ],
    aliases: ['CALL M'],
    addressing: 'absolute',
  },
  {
    mnemonic: 'RET',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 201 }],
  },
  {
    mnemonic: 'RET',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 192 }],
    aliases: ['RET NZ'],
  },
  {
    mnemonic: 'RET',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 200 }],
    aliases: ['RET Z'],
  },
  {
    mnemonic: 'RET',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 208 }],
    aliases: ['RET NC'],
  },
  {
    mnemonic: 'RET',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 216 }],
    aliases: ['RET C'],
  },
  {
    mnemonic: 'RET',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 224 }],
    aliases: ['RET PO'],
  },
  {
    mnemonic: 'RET',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 232 }],
    aliases: ['RET PE'],
  },
  {
    mnemonic: 'RET',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 240 }],
    aliases: ['RET P'],
  },
  {
    mnemonic: 'RET',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 248 }],
    aliases: ['RET M'],
  },
  {
    mnemonic: 'RETI',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 77 },
    ],
  },
  {
    mnemonic: 'RETN',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 69 },
    ],
  },
  {
    mnemonic: 'PUSH',
    operands: ['BC'],
    opcodeEntries: [{ kind: 'fixed', value: 197 }],
  },
  {
    mnemonic: 'PUSH',
    operands: ['DE'],
    opcodeEntries: [{ kind: 'fixed', value: 213 }],
  },
  {
    mnemonic: 'PUSH',
    operands: ['HL'],
    opcodeEntries: [{ kind: 'fixed', value: 229 }],
  },
  {
    mnemonic: 'PUSH',
    operands: ['AF'],
    opcodeEntries: [{ kind: 'fixed', value: 245 }],
  },
  {
    mnemonic: 'POP',
    operands: ['BC'],
    opcodeEntries: [{ kind: 'fixed', value: 193 }],
  },
  {
    mnemonic: 'POP',
    operands: ['DE'],
    opcodeEntries: [{ kind: 'fixed', value: 209 }],
  },
  {
    mnemonic: 'POP',
    operands: ['HL'],
    opcodeEntries: [{ kind: 'fixed', value: 225 }],
  },
  {
    mnemonic: 'POP',
    operands: ['AF'],
    opcodeEntries: [{ kind: 'fixed', value: 241 }],
  },
  {
    mnemonic: 'RST',
    operands: ['0x00'],
    opcodeEntries: [{ kind: 'fixed', value: 199 }],
  },
  {
    mnemonic: 'RST',
    operands: ['0x08'],
    opcodeEntries: [{ kind: 'fixed', value: 207 }],
  },
  {
    mnemonic: 'RST',
    operands: ['0x10'],
    opcodeEntries: [{ kind: 'fixed', value: 215 }],
  },
  {
    mnemonic: 'RST',
    operands: ['0x18'],
    opcodeEntries: [{ kind: 'fixed', value: 223 }],
  },
  {
    mnemonic: 'RST',
    operands: ['0x20'],
    opcodeEntries: [{ kind: 'fixed', value: 231 }],
  },
  {
    mnemonic: 'RST',
    operands: ['0x28'],
    opcodeEntries: [{ kind: 'fixed', value: 239 }],
  },
  {
    mnemonic: 'RST',
    operands: ['0x30'],
    opcodeEntries: [{ kind: 'fixed', value: 247 }],
  },
  {
    mnemonic: 'RST',
    operands: ['0x38'],
    opcodeEntries: [{ kind: 'fixed', value: 255 }],
  },
  {
    mnemonic: 'EX',
    operands: ['AF', "AF'"],
    opcodeEntries: [{ kind: 'fixed', value: 8 }],
  },
  {
    mnemonic: 'EX',
    operands: ['DE', 'HL'],
    opcodeEntries: [{ kind: 'fixed', value: 235 }],
  },
  {
    mnemonic: 'EX',
    operands: ['(SP)', 'HL'],
    opcodeEntries: [{ kind: 'fixed', value: 227 }],
  },
  {
    mnemonic: 'EXX',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 217 }],
  },
  {
    mnemonic: 'RLCA',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 7 }],
  },
  {
    mnemonic: 'RRCA',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 15 }],
  },
  {
    mnemonic: 'RLA',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 23 }],
  },
  {
    mnemonic: 'RRA',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 31 }],
  },
  {
    mnemonic: 'RRD',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 103 },
    ],
  },
  {
    mnemonic: 'RLD',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 111 },
    ],
  },
  {
    mnemonic: 'DAA',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 39 }],
  },
  {
    mnemonic: 'CPL',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 47 }],
  },
  {
    mnemonic: 'NEG',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 68 },
    ],
  },
  {
    mnemonic: 'SCF',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 55 }],
  },
  {
    mnemonic: 'CCF',
    operands: [],
    opcodeEntries: [{ kind: 'fixed', value: 63 }],
  },
  {
    mnemonic: 'IM',
    operands: ['0'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 70 },
    ],
  },
  {
    mnemonic: 'IM',
    operands: ['1'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 86 },
    ],
  },
  {
    mnemonic: 'IM',
    operands: ['2'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 94 },
    ],
  },
  {
    mnemonic: 'IN',
    operands: ['A', '(imm)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 219 },
      { kind: 'ref', identifier: 'PORT_u8' },
    ],
  },
  {
    mnemonic: 'IN',
    operands: ['B', '(C)'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 64 },
    ],
  },
  {
    mnemonic: 'IN',
    operands: ['C', '(C)'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 72 },
    ],
  },
  {
    mnemonic: 'IN',
    operands: ['D', '(C)'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 80 },
    ],
  },
  {
    mnemonic: 'IN',
    operands: ['E', '(C)'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 88 },
    ],
  },
  {
    mnemonic: 'IN',
    operands: ['H', '(C)'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 96 },
    ],
  },
  {
    mnemonic: 'IN',
    operands: ['L', '(C)'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 104 },
    ],
  },
  {
    mnemonic: 'IN',
    operands: ['A', '(C)'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 120 },
    ],
  },
  {
    mnemonic: 'IN',
    operands: ['(C)'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 112 },
    ],
  },
  {
    mnemonic: 'OUT',
    operands: ['(imm)', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 211 },
      { kind: 'ref', identifier: 'PORT_u8' },
    ],
  },
  {
    mnemonic: 'OUT',
    operands: ['(C)', 'B'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 65 },
    ],
  },
  {
    mnemonic: 'OUT',
    operands: ['(C)', 'C'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 73 },
    ],
  },
  {
    mnemonic: 'OUT',
    operands: ['(C)', 'D'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 81 },
    ],
  },
  {
    mnemonic: 'OUT',
    operands: ['(C)', 'E'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 89 },
    ],
  },
  {
    mnemonic: 'OUT',
    operands: ['(C)', 'H'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 97 },
    ],
  },
  {
    mnemonic: 'OUT',
    operands: ['(C)', 'L'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 105 },
    ],
  },
  {
    mnemonic: 'OUT',
    operands: ['(C)', 'A'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 121 },
    ],
  },
  {
    mnemonic: 'OUT',
    operands: ['(C)', '0'],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 113 },
    ],
  },
  {
    mnemonic: 'LDI',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 160 },
    ],
  },
  {
    mnemonic: 'LDD',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 168 },
    ],
  },
  {
    mnemonic: 'LDIR',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 176 },
    ],
  },
  {
    mnemonic: 'LDDR',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 184 },
    ],
  },
  {
    mnemonic: 'CPI',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 161 },
    ],
  },
  {
    mnemonic: 'CPD',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 169 },
    ],
  },
  {
    mnemonic: 'CPIR',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 177 },
    ],
  },
  {
    mnemonic: 'CPDR',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 185 },
    ],
  },
  {
    mnemonic: 'INI',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 162 },
    ],
  },
  {
    mnemonic: 'IND',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 170 },
    ],
  },
  {
    mnemonic: 'INIR',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 178 },
    ],
  },
  {
    mnemonic: 'INDR',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 186 },
    ],
  },
  {
    mnemonic: 'OUTI',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 163 },
    ],
  },
  {
    mnemonic: 'OUTD',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 171 },
    ],
  },
  {
    mnemonic: 'OTIR',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 179 },
    ],
  },
  {
    mnemonic: 'OTDR',
    operands: [],
    opcodeEntries: [
      { kind: 'fixed', value: 237 },
      { kind: 'fixed', value: 187 },
    ],
  },
  {
    mnemonic: 'RLC',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 0 },
    ],
  },
  {
    mnemonic: 'RLC',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 1 },
    ],
  },
  {
    mnemonic: 'RLC',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 2 },
    ],
  },
  {
    mnemonic: 'RLC',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 3 },
    ],
  },
  {
    mnemonic: 'RLC',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 4 },
    ],
  },
  {
    mnemonic: 'RLC',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 5 },
    ],
  },
  {
    mnemonic: 'RLC',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 6 },
    ],
  },
  {
    mnemonic: 'RLC',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 7 },
    ],
  },
  {
    mnemonic: 'RRC',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 8 },
    ],
  },
  {
    mnemonic: 'RRC',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 9 },
    ],
  },
  {
    mnemonic: 'RRC',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 10 },
    ],
  },
  {
    mnemonic: 'RRC',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 11 },
    ],
  },
  {
    mnemonic: 'RRC',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 12 },
    ],
  },
  {
    mnemonic: 'RRC',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 13 },
    ],
  },
  {
    mnemonic: 'RRC',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 14 },
    ],
  },
  {
    mnemonic: 'RRC',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 15 },
    ],
  },
  {
    mnemonic: 'RL',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 16 },
    ],
  },
  {
    mnemonic: 'RL',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 17 },
    ],
  },
  {
    mnemonic: 'RL',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 18 },
    ],
  },
  {
    mnemonic: 'RL',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 19 },
    ],
  },
  {
    mnemonic: 'RL',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 20 },
    ],
  },
  {
    mnemonic: 'RL',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 21 },
    ],
  },
  {
    mnemonic: 'RL',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 22 },
    ],
  },
  {
    mnemonic: 'RL',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 23 },
    ],
  },
  {
    mnemonic: 'RR',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 24 },
    ],
  },
  {
    mnemonic: 'RR',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 25 },
    ],
  },
  {
    mnemonic: 'RR',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 26 },
    ],
  },
  {
    mnemonic: 'RR',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 27 },
    ],
  },
  {
    mnemonic: 'RR',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 28 },
    ],
  },
  {
    mnemonic: 'RR',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 29 },
    ],
  },
  {
    mnemonic: 'RR',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 30 },
    ],
  },
  {
    mnemonic: 'RR',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 31 },
    ],
  },
  {
    mnemonic: 'SLA',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 32 },
    ],
  },
  {
    mnemonic: 'SLA',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 33 },
    ],
  },
  {
    mnemonic: 'SLA',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 34 },
    ],
  },
  {
    mnemonic: 'SLA',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 35 },
    ],
  },
  {
    mnemonic: 'SLA',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 36 },
    ],
  },
  {
    mnemonic: 'SLA',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 37 },
    ],
  },
  {
    mnemonic: 'SLA',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 38 },
    ],
  },
  {
    mnemonic: 'SLA',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 39 },
    ],
  },
  {
    mnemonic: 'SRA',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 40 },
    ],
  },
  {
    mnemonic: 'SRA',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 41 },
    ],
  },
  {
    mnemonic: 'SRA',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 42 },
    ],
  },
  {
    mnemonic: 'SRA',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 43 },
    ],
  },
  {
    mnemonic: 'SRA',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 44 },
    ],
  },
  {
    mnemonic: 'SRA',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 45 },
    ],
  },
  {
    mnemonic: 'SRA',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 46 },
    ],
  },
  {
    mnemonic: 'SRA',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 47 },
    ],
  },
  {
    mnemonic: 'SRL',
    operands: ['B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 56 },
    ],
  },
  {
    mnemonic: 'SRL',
    operands: ['C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 57 },
    ],
  },
  {
    mnemonic: 'SRL',
    operands: ['D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 58 },
    ],
  },
  {
    mnemonic: 'SRL',
    operands: ['E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 59 },
    ],
  },
  {
    mnemonic: 'SRL',
    operands: ['H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 60 },
    ],
  },
  {
    mnemonic: 'SRL',
    operands: ['L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 61 },
    ],
  },
  {
    mnemonic: 'SRL',
    operands: ['(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 62 },
    ],
  },
  {
    mnemonic: 'SRL',
    operands: ['A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 63 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['0', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 64 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['0', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 65 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['0', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 66 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['0', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 67 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['0', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 68 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['0', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 69 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['0', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 70 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['0', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 71 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['1', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 72 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['1', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 73 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['1', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 74 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['1', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 75 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['1', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 76 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['1', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 77 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['1', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 78 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['1', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 79 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['2', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 80 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['2', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 81 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['2', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 82 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['2', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 83 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['2', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 84 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['2', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 85 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['2', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 86 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['2', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 87 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['3', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 88 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['3', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 89 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['3', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 90 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['3', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 91 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['3', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 92 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['3', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 93 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['3', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 94 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['3', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 95 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['4', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 96 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['4', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 97 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['4', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 98 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['4', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 99 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['4', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 100 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['4', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 101 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['4', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 102 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['4', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 103 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['5', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 104 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['5', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 105 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['5', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 106 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['5', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 107 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['5', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 108 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['5', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 109 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['5', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 110 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['5', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 111 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['6', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 112 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['6', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 113 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['6', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 114 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['6', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 115 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['6', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 116 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['6', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 117 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['6', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 118 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['6', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 119 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['7', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 120 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['7', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 121 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['7', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 122 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['7', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 123 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['7', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 124 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['7', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 125 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['7', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 126 },
    ],
  },
  {
    mnemonic: 'BIT',
    operands: ['7', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 127 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['0', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 128 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['0', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 129 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['0', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 130 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['0', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 131 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['0', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 132 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['0', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 133 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['0', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 134 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['0', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 135 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['1', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 136 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['1', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 137 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['1', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 138 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['1', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 139 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['1', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 140 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['1', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 141 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['1', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 142 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['1', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 143 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['2', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 144 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['2', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 145 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['2', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 146 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['2', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 147 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['2', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 148 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['2', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 149 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['2', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 150 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['2', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 151 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['3', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 152 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['3', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 153 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['3', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 154 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['3', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 155 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['3', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 156 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['3', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 157 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['3', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 158 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['3', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 159 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['4', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 160 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['4', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 161 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['4', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 162 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['4', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 163 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['4', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 164 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['4', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 165 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['4', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 166 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['4', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 167 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['5', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 168 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['5', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 169 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['5', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 170 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['5', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 171 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['5', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 172 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['5', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 173 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['5', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 174 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['5', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 175 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['6', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 176 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['6', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 177 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['6', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 178 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['6', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 179 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['6', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 180 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['6', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 181 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['6', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 182 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['6', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 183 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['7', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 184 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['7', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 185 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['7', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 186 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['7', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 187 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['7', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 188 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['7', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 189 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['7', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 190 },
    ],
  },
  {
    mnemonic: 'RES',
    operands: ['7', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 191 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['0', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 192 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['0', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 193 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['0', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 194 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['0', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 195 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['0', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 196 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['0', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 197 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['0', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 198 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['0', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 199 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['1', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 200 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['1', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 201 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['1', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 202 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['1', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 203 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['1', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 204 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['1', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 205 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['1', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 206 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['1', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 207 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['2', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 208 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['2', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 209 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['2', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 210 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['2', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 211 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['2', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 212 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['2', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 213 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['2', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 214 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['2', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 215 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['3', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 216 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['3', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 217 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['3', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 218 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['3', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 219 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['3', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 220 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['3', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 221 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['3', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 222 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['3', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 223 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['4', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 224 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['4', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 225 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['4', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 226 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['4', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 227 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['4', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 228 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['4', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 229 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['4', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 230 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['4', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 231 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['5', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 232 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['5', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 233 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['5', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 234 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['5', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 235 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['5', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 236 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['5', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 237 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['5', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 238 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['5', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 239 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['6', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 240 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['6', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 241 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['6', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 242 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['6', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 243 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['6', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 244 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['6', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 245 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['6', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 246 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['6', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 247 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['7', 'B'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 248 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['7', 'C'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 249 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['7', 'D'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 250 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['7', 'E'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 251 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['7', 'H'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 252 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['7', 'L'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 253 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['7', '(HL)'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 254 },
    ],
  },
  {
    mnemonic: 'SET',
    operands: ['7', 'A'],
    operandSize: 8,
    opcodeEntries: [
      { kind: 'fixed', value: 203 },
      { kind: 'fixed', value: 255 },
    ],
  },
];
