import type { InstructionInfo } from '@rawrs/architecture/Target';

import { Opcodes } from '../opcodes';

export const adc: InstructionInfo = {
  identifier: 'adc',
  name: 'Integer Addition With Carry',
  description:
    '`ADD` and `ADC` perform an integer addition on the two operands. The `ADC` instruction also adds in the initial state of the carry flag. The result of the addition goes to the first operand. `ADC` is usually executed as part of a multi-byte or multi-word addition operation. When a byte immediate value is added to a word operand, the immediate value is first sign-extended.',
  modifies: ['OF', 'SF', 'ZF', 'AF', 'PF', 'CF'],
  undefined: [],
  macros: {
    ALU8_OP: [
      'b = b + CARRY',
      'alu_result = a + b',
      'flag_op = ${FLAG_OP_ALU} | CARRY | ${FLAG_OP_8BIT}',
    ],
    ALU16_OP: [
      'b = b + CARRY',
      'alu_result = a + b',
      'flag_op = ${FLAG_OP_ALU} | CARRY | ${FLAG_OP_16BIT}',
    ],
  },
  locals: [
    {
      identifier: 'effective_address',
      name: 'Effective Address',
      size: 32,
    },
  ],
  forms: [
    // Opcodes.ADC_EB_RB /r - ADC eb, rb
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ADC_EB_RB, 'ModRM_110_reg_00', 'DISP_i16'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u8[effective_address]',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ADC_EB_RB, 'ModRM_rm_reg_00'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ADC_EB_RB, 'ModRM_rm_reg_01', 'DISP_i8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ADC_EB_RB, 'ModRM_rm_reg_10', 'DISP_i16'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM8}',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = alu_result',
      ],
      opcode: [Opcodes.ADC_EB_RB, 'ModRM_rm_reg_11'],
      operandSize: 8,
      cycles: 2,
    },
    // Opcodes.ADC_EW_RW /r - ADC ew, rw
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ADC_EW_RW, 'ModRM_110_reg_00', 'DISP_i16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u16[effective_address]',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ADC_EW_RW, 'ModRM_rm_reg_00'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ADC_EW_RW, 'ModRM_rm_reg_01', 'DISP_i8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ADC_EW_RW, 'ModRM_rm_reg_10', 'DISP_i16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM16}',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = alu_result',
      ],
      opcode: [Opcodes.ADC_EW_RW, 'ModRM_rm_reg_11'],
      operandSize: 16,
      cycles: 2,
    },
    // Opcodes.ADC_RB_EB /r - ADC rb, eb
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = ${MOD_RM_REG8}',
        'b = RAM:u8[effective_address]',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.ADC_RB_EB, 'ModRM_110_reg_00', 'DISP_i16'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = ${MOD_RM_REG8}',
        'b = RAM:u8[effective_address]',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.ADC_RB_EB, 'ModRM_rm_reg_00'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = ${MOD_RM_REG8}',
        'b = RAM:u8[effective_address]',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.ADC_RB_EB, 'ModRM_rm_reg_01', 'DISP_i8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = ${MOD_RM_REG8}',
        'b = RAM:u8[effective_address]',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.ADC_RB_EB, 'ModRM_rm_reg_10', 'DISP_i16'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_REG8}',
        'b = ${MOD_RM_RM8}',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.ADC_RB_EB, 'ModRM_rm_reg_11'],
      operandSize: 8,
      cycles: 2,
    },
    // Opcodes.ADC_RW_EW /r - ADC rw, ew
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = ${MOD_RM_REG16}',
        'b = RAM:u16[effective_address]',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.ADC_RW_EW, 'ModRM_110_reg_00', 'DISP_i16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = ${MOD_RM_REG16}',
        'b = RAM:u16[effective_address]',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.ADC_RW_EW, 'ModRM_rm_reg_00'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = ${MOD_RM_REG16}',
        'b = RAM:u16[effective_address]',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.ADC_RW_EW, 'ModRM_rm_reg_01', 'DISP_i8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = ${MOD_RM_REG16}',
        'b = RAM:u16[effective_address]',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.ADC_RW_EW, 'ModRM_rm_reg_10', 'DISP_i16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_REG16}',
        'b = ${MOD_RM_RM16}',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.ADC_RW_EW, 'ModRM_rm_reg_11'],
      operandSize: 16,
      cycles: 2,
    },
    // 0x14 db - ADC AL, db
    {
      operation: [
        '${RESOLVE_CF}',
        'a = AL',
        'b = %{IMM}',
        '${ALU8_OP}',
        'AL = alu_result',
      ],
      opcode: [Opcodes.ADC_AL_DB, 'IMM_u8'],
      operandSize: 8,
      cycles: 3,
    },
    // 0x15 dw - ADC AX, dw
    {
      operation: [
        '${RESOLVE_CF}',
        'a = AX',
        'b = %{IMM}',
        '${ALU16_OP}',
        'AX = alu_result',
      ],
      opcode: [Opcodes.ADC_AX_DW, 'IMM_u16'],
      operandSize: 16,
      cycles: 3,
    },
    // 0x80 /2 db - ADC eb, db
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = %{IMM}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_110_010_00', 'DISP_i16', 'IMM_u8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u8[effective_address]',
        'b = %{IMM}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_rm_010_00', 'IMM_u8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = %{IMM}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_rm_010_01', 'DISP_i8', 'IMM_u8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = %{IMM}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_rm_010_10', 'DISP_i16', 'IMM_u8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM8}',
        'b = %{IMM}',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_rm_010_11', 'IMM_u8'],
      operandSize: 8,
      cycles: 3,
    },
    // 0x81 /2 dw - ADC ew, dw
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_110_010_00', 'DISP_i16', 'IMM_u16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_rm_010_00', 'IMM_u16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_rm_010_01', 'DISP_i8', 'IMM_u16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_rm_010_10', 'DISP_i16', 'IMM_u16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM16}',
        'b = %{IMM}',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_rm_010_11', 'IMM_u16'],
      operandSize: 16,
      cycles: 3,
    },
    // 0x83 /2 db - ADC ew, db
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_110_010_00', 'DISP_i16', 'IMM_u8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_rm_010_00', 'IMM_u8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_rm_010_01', 'DISP_i8', 'IMM_u8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_rm_010_10', 'DISP_i16', 'IMM_u8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM16}',
        'b = %{IMM}',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_rm_010_11', 'IMM_u8'],
      operandSize: 16,
      cycles: 3,
    },
  ],
};
