import type { InstructionInfo } from '@machinery/core';
import { InstructionDataTypes } from '@machinery/core';

import { Opcodes } from '../opcodes';

export const call: InstructionInfo = {
  identifier: 'call',
  name: 'Call',
  description: '',
  modifies: [],
  undefined: [],
  locals: [
    {
      identifier: 'effective_address',
      name: 'Effective Address',
      size: 32,
    },
    {
      identifier: 'offset',
      name: 'Effective Offset',
      size: 32,
    },
    {
      identifier: 'stack_address',
      name: 'Effective Stack Address',
      size: 32,
    },
    {
      identifier: 'tmp',
      name: 'Temporary register',
      size: 16,
    },
  ],
  forms: [
    // 0xe8 cw - CALL cw
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'IP = IP + %{imm}',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'IP = IP + %{imm}',
          ],
        },
      },
      opcode: [Opcodes.CALL_CW, 'IMM_i16'],
      operands: ['rel'],
      operandSize: 8,
      distance: 'near',
      addressing: 'relative',
      cycles: 7,
    },
    // 0xFF /2 - CALL ew
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_110_010_00', 'DISP_i16'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_010_00'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET} + %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET} + %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_010_01', 'DISP_i8'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET} + %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET} + %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_010_10', 'DISP_i16'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'IP = ${MOD_RM_RM16}',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'IP = ${MOD_RM_RM16}',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm16_010_11'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 7,
    },
    // 0x9a cd - CALL cd
    // TODO: deal with selector access rights bits (AR)
    // TODO: use a setter for the segment selector so we can get the base and raise exceptions
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'CS = NEW_CS',
            'IP = NEW_IP',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 3) < SS_LIMIT_MIN',
            '#GP if (tmp + 3) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'CS = NEW_CS',
            'IP = NEW_IP',
          ],
        },
      },
      opcode: [
        Opcodes.CALL_CD,
        {
          identifier: 'NEW_IP',
          name: 'New IP Value',
          type: InstructionDataTypes.Immediate,
          size: 16,
        },
        {
          identifier: 'NEW_CS',
          name: 'New CS Value',
          type: InstructionDataTypes.Immediate,
          size: 16,
        },
      ],
      operands: ['ptr'],
      operandSize: 8,
      distance: 'far',
      addressing: 'absolute',
      cycles: 7,
    },
    // 0xFF /3 - CALL ed
    // TODO: deal with selector access rights bits (AR)
    // TODO: use a setter for the segment selector so we can get the base and raise exceptions
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 3) < SS_LIMIT_MIN',
            '#GP if (tmp + 3) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_110_011_00', 'DISP_i16'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 3) < SS_LIMIT_MIN',
            '#GP if (tmp + 3) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_011_00'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET} + %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 3) < SS_LIMIT_MIN',
            '#GP if (tmp + 3) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET} + %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_011_01', 'DISP_i8'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET} + %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 3) < SS_LIMIT_MIN',
            '#GP if (tmp + 3) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = ${MOD_RM_OFFSET} + %{DISP}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_011_10', 'DISP_i16'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'effective_address = ${MOD_RM_RM16}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 3) < SS_LIMIT_MIN',
            '#GP if (tmp + 3) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'effective_address = ${MOD_RM_RM16}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm16_011_11'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 7,
    },
  ],
};
