import type { InstructionInfo } from '@machinery/core';
import { InstructionDataTypes } from '@machinery/core';

import { Opcodes } from '../opcodes';

export const call: InstructionInfo = {
  identifier: 'call',
  name: 'Call',
  description: '',
  modifies: [],
  undefined: [],
  macros: {
    // Protected-mode far CALL logic — handles both direct code segment calls
    // and call gate transitions (same privilege and privilege change).
    // Expects locals: gate_sel, gate_off, stack_address, tmp, index,
    //   desc_type, desc_s, desc_a, desc_dpl, desc_p, desc_limit, desc_base,
    //   gate_target_sel, gate_target_off, gate_word_count, new_cpl,
    //   old_cs, old_ip, old_ss, old_sp, old_stack_addr, new_ss, new_sp.
    CALL_FAR_PROTECTED: [
      ';; Look up the descriptor for the selector',
      'tmp = gate_sel',
      'index = tmp >> 3',
      'ERROR_CODE = gate_sel',
      '#GP if index == 0',
      '${DESCRIPTOR_BOUNDS_CHECK}',
      '${LOAD_DESCRIPTOR_FIELDS}',
      '${LOAD_DESCRIPTOR_A}',

      ';; Save old state before any modifications',
      'old_cs = CS',
      'old_ip = IP',
      'old_ss = SS',
      'old_sp = SP',

      ';; === DIRECT CODE SEGMENT CALL (S=1) ===',
      'if desc_s == 1',
      [
        ';; Must be executable code segment',
        '#GP if (desc_type & 0b100) != 0b100',
        ';; Non-conforming: DPL must equal CPL',
        'if (desc_type & 0b010) != 0b010',
        ['#GP if desc_dpl != CS.RPL'],
        'end if',
        ';; Conforming: DPL must be <= CPL',
        'if (desc_type & 0b010) == 0b010',
        ['#GP if desc_dpl > CS.RPL'],
        'end if',
        ';; Must be present',
        '#NP if desc_p != 1',
        ';; Push old CS:IP on current stack',
        'tmp = old_sp - 4',
        'stack_address = SS_BASE + tmp',
        '#SS if (tmp + 3) < SS_LIMIT_MIN',
        '#SS if (tmp + 3) > SS_LIMIT_MAX',
        'RAM:u16[stack_address] = old_ip',
        'RAM:u16[stack_address + 2] = old_cs',
        'SP = tmp',
        ';; Load new CS:IP via setter',
        'CS = gate_sel',
        'IP = gate_off',
      ],
      'end if',

      ';; === SYSTEM DESCRIPTOR (S=0) ===',
      'if desc_s == 0',
      [
        ';; === CALL GATE (A=0, type=010) ===',
        'if desc_a == 0',
        [
          '#GP if desc_type != 0b010',
          ';; Gate DPL must be >= CPL',
          '#GP if desc_dpl < CS.RPL',
          ';; Gate DPL must be >= selector RPL',
          '#GP if desc_dpl < (gate_sel & 0x0003)',
          ';; Gate must be present',
          '#NP if desc_p != 1',

          ';; Read call gate descriptor fields',
          '${LOAD_CALL_GATE_FIELDS}',

          ';; Look up target code segment',
          'tmp = gate_target_sel',
          'index = tmp >> 3',
          'ERROR_CODE = gate_target_sel',
          '#GP if index == 0',
          '${DESCRIPTOR_BOUNDS_CHECK}',
          '${LOAD_DESCRIPTOR_FIELDS}',
          ';; Must be code segment (S=1, executable)',
          '#GP if desc_s != 1',
          '#GP if (desc_type & 0b100) != 0b100',
          ';; Target DPL must be <= CPL',
          '#GP if desc_dpl > CS.RPL',
          ';; Must be present',
          '#NP if desc_p != 1',

          ';; Determine new CPL',
          'new_cpl = desc_dpl',
          ';; For conforming code, CPL does not change',
          'if (desc_type & 0b010) == 0b010',
          ['new_cpl = CS.RPL'],
          'end if',

          ';; Save old stack address for parameter copy',
          'old_stack_addr = SS_BASE + old_sp',

          ';; === SAME PRIVILEGE CALL GATE ===',
          'if new_cpl == CS.RPL',
          [
            ';; Push old CS:IP on current stack',
            'tmp = old_sp - 4',
            'stack_address = SS_BASE + tmp',
            '#SS if (tmp + 3) < SS_LIMIT_MIN',
            '#SS if (tmp + 3) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = old_ip',
            'RAM:u16[stack_address + 2] = old_cs',
            'SP = tmp',
            ';; Load new CS:IP',
            'CS = (gate_target_sel & 0xFFFC) | new_cpl',
            'IP = gate_target_off',
          ],
          'end if',

          ';; === PRIVILEGE TRANSITION CALL GATE ===',
          'if new_cpl < CS.RPL',
          [
            ';; Read new SS:SP from TSS based on target privilege level',
            '${CALL_GATE_READ_TSS_STACK}',

            ';; Load new CS first (sets CS.RPL = new_cpl, needed for SS setter DPL check)',
            'CS = (gate_target_sel & 0xFFFC) | new_cpl',

            ';; Load new SS (setter validates DPL == CS.RPL and loads cache)',
            ';; TODO: i286 spec says invalid new SS should raise #TS, not #GP',
            'SS = (new_ss & 0xFFFC) | new_cpl',

            ';; Build stack frame on new stack',
            ';; Layout (low to high): old_IP, old_CS, params[0..N-1], old_SP, old_SS',
            'SP = new_sp - 8 - (gate_word_count * 2)',
            'stack_address = SS_BASE + SP',
            ';; Check new stack limits',
            '#SS if SP < SS_LIMIT_MIN',
            '#SS if (SP + 7 + gate_word_count * 2) > SS_LIMIT_MAX',
            ';; Write return info at bottom of frame',
            'RAM:u16[stack_address] = old_ip',
            'RAM:u16[stack_address + 2] = old_cs',
            ';; Write old SS:SP at top of frame',
            'RAM:u16[stack_address + 4 + gate_word_count * 2] = old_sp',
            'RAM:u16[stack_address + 6 + gate_word_count * 2] = old_ss',
            ';; Copy parameters from old stack to new stack',
            '${CALL_GATE_COPY_PARAMS}',
            ';; Set IP to gate target',
            'IP = gate_target_off',
          ],
          'end if',
        ],
        'end if',

        ';; === TSS OR TASK GATE (A=1) ===',
        'if desc_a == 1',
        [
          ';; Reject invalid types (must be available TSS type=000 or task gate type=010)',
          'if desc_type != 0b000 && desc_type != 0b010',
          ['#GP if desc_type != 0b000'],
          'end if',
          ';; DPL must be >= CPL',
          '#GP if desc_dpl < CS.RPL',
          ';; DPL must be >= selector RPL',
          '#GP if desc_dpl < (gate_sel & 0x0003)',
          ';; Must be present',
          '#NP if desc_p != 1',

          ';; === AVAILABLE TSS (type=000) — direct task switch ===',
          'if desc_type == 0b000',
          [
            'tss_sel = gate_sel',
            'tss_index = index',
            'task_nesting = 1',
            '${TASK_SWITCH}',
          ],
          'end if',

          ';; === TASK GATE (type=010) — indirect task switch ===',
          'if desc_type == 0b010',
          [
            ';; Read TSS selector from task gate',
            '${LOAD_TASK_GATE_FIELDS}',
            ';; Validate TSS selector',
            'ERROR_CODE = tss_sel',
            ';; Must be in GDT (TI bit = 0)',
            '#GP if (tss_sel & 0x0004) != 0',
            'tss_index = tss_sel >> 3',
            '#GP if tss_index == 0',
            '#GP if (tss_index * 8) > GDTR.limit',
            ';; Must be available TSS (S=0, A=1, type=000)',
            '#GP if RAM.GDT.gates[tss_index].SD.S != 0',
            '#GP if RAM.GDT.gates[tss_index].SD.A != 1',
            '#GP if RAM.GDT.gates[tss_index].SD.type != 0b000',
            ';; Must be present',
            '#NP if RAM.GDT.gates[tss_index].SD.P != 1',
            ';; Load TSS descriptor fields for TASK_SWITCH',
            'desc_base = RAM.GDT.gates[tss_index].SD.base',
            'desc_limit = RAM.GDT.gates[tss_index].SD.limit',
            'task_nesting = 1',
            '${TASK_SWITCH}',
          ],
          'end if',
        ],
        'end if',
      ],
      'end if',
    ],
  },
  locals: [
    {
      identifier: 'effective_address',
      name: 'Effective Address',
      size: 32,
    },
    {
      identifier: 'offset',
      name: 'Effective Offset',
      size: 32,
    },
    {
      identifier: 'stack_address',
      name: 'Effective Stack Address',
      size: 32,
    },
    {
      identifier: 'tmp',
      name: 'Temporary register',
      size: 16,
    },
    // Protected-mode call gate support
    {
      identifier: 'gate_sel',
      name: 'Far call selector',
      size: 16,
    },
    {
      identifier: 'gate_off',
      name: 'Far call offset',
      size: 16,
    },
    {
      identifier: 'index',
      name: 'Descriptor table entry index',
      size: 16,
    },
    {
      identifier: 'desc_type',
      name: 'Descriptor type field',
      size: 8,
    },
    {
      identifier: 'desc_s',
      name: 'Descriptor S bit',
      size: 8,
    },
    {
      identifier: 'desc_a',
      name: 'Descriptor A bit',
      size: 8,
    },
    {
      identifier: 'desc_dpl',
      name: 'Descriptor privilege level',
      size: 8,
    },
    {
      identifier: 'desc_p',
      name: 'Descriptor present bit',
      size: 8,
    },
    {
      identifier: 'desc_limit',
      name: 'Descriptor limit',
      size: 16,
    },
    {
      identifier: 'desc_base',
      name: 'Descriptor base',
      size: 32,
    },
    {
      identifier: 'gate_target_sel',
      name: 'Call gate target CS selector',
      size: 16,
    },
    {
      identifier: 'gate_target_off',
      name: 'Call gate target IP offset',
      size: 16,
    },
    {
      identifier: 'gate_word_count',
      name: 'Call gate parameter word count',
      size: 8,
    },
    {
      identifier: 'new_cpl',
      name: 'New CPL (target privilege level)',
      size: 8,
    },
    {
      identifier: 'old_cs',
      name: 'Saved CS before call',
      size: 16,
    },
    {
      identifier: 'old_ip',
      name: 'Saved IP before call',
      size: 16,
    },
    {
      identifier: 'old_ss',
      name: 'Saved SS before call',
      size: 16,
    },
    {
      identifier: 'old_sp',
      name: 'Saved SP before call',
      size: 16,
    },
    {
      identifier: 'old_stack_addr',
      name: 'Old stack linear address',
      size: 32,
    },
    {
      identifier: 'new_ss',
      name: 'New SS from TSS',
      size: 16,
    },
    {
      identifier: 'new_sp',
      name: 'New SP from TSS',
      size: 16,
    },
    // Task switch support
    {
      identifier: 'tss_sel',
      name: 'Target TSS selector',
      size: 16,
    },
    {
      identifier: 'tss_index',
      name: 'Target TSS GDT index',
      size: 16,
    },
    {
      identifier: 'old_tss_index',
      name: 'Old TSS GDT index',
      size: 16,
    },
    {
      identifier: 'old_tr_sel',
      name: 'Old TR selector (before switch)',
      size: 16,
    },
    {
      identifier: 'task_nesting',
      name: 'Task nesting flag (1=CALL, 0=JMP)',
      size: 8,
    },
    {
      identifier: 'ldtr_sel',
      name: 'LDTR selector from new TSS',
      size: 16,
    },
    {
      identifier: 'ldtr_index',
      name: 'LDTR GDT index',
      size: 16,
    },
  ],
  forms: [
    // 0xe8 cw - CALL cw
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'IP = IP + %{imm}',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'IP = IP + %{imm}',
          ],
        },
      },
      opcode: [Opcodes.CALL_CW, 'IMM_i16'],
      operands: ['rel'],
      operandSize: 8,
      distance: 'near',
      addressing: 'relative',
      cycles: 7,
    },
    // 0xFF /2 - CALL ew
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = %{DISP:u16}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = %{DISP:u16}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_110_010_00', 'DISP_i16'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = (${MOD_RM_OFFSET}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = (${MOD_RM_OFFSET}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_010_00'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = (${MOD_RM_OFFSET} + %{DISP}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = (${MOD_RM_OFFSET} + %{DISP}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_010_01', 'DISP_i8'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = (${MOD_RM_OFFSET} + %{DISP}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'offset = (${MOD_RM_OFFSET} + %{DISP}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'IP = RAM:u16[effective_address]',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_010_10', 'DISP_i16'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'IP = ${MOD_RM_RM16}',
          ],
        },
        protected: {
          operation: [
            'tmp = SP - 2',
            'stack_address = SS_BASE + tmp',
            '#GP if (tmp + 1) < SS_LIMIT_MIN',
            '#GP if (tmp + 1) > SS_LIMIT_MAX',
            'RAM:u16[stack_address] = IP',
            'SP = tmp',
            'IP = ${MOD_RM_RM16}',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm16_010_11'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'near',
      addressing: 'absolute',
      cycles: 7,
    },
    // 0x9a cd - CALL cd
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'CS = NEW_CS',
            'IP = NEW_IP',
          ],
        },
        protected: {
          operation: [
            'gate_sel = NEW_CS',
            'gate_off = NEW_IP',
            '${CALL_FAR_PROTECTED}',
          ],
        },
      },
      opcode: [
        Opcodes.CALL_CD,
        {
          identifier: 'NEW_IP',
          name: 'New IP Value',
          type: InstructionDataTypes.Immediate,
          size: 16,
        },
        {
          identifier: 'NEW_CS',
          name: 'New CS Value',
          type: InstructionDataTypes.Immediate,
          size: 16,
        },
      ],
      operands: ['ptr'],
      operandSize: 8,
      distance: 'far',
      addressing: 'absolute',
      cycles: 7,
    },
    // 0xFF /3 - CALL ed (far indirect through memory)
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = %{DISP:u16}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'offset = %{DISP:u16}',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'gate_off = RAM:u16[effective_address]',
            'gate_sel = RAM:u16[effective_address + 2]',
            '${CALL_FAR_PROTECTED}',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_110_011_00', 'DISP_i16'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = (${MOD_RM_OFFSET}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'offset = (${MOD_RM_OFFSET}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'gate_off = RAM:u16[effective_address]',
            'gate_sel = RAM:u16[effective_address + 2]',
            '${CALL_FAR_PROTECTED}',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_011_00'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = (${MOD_RM_OFFSET} + %{DISP}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'offset = (${MOD_RM_OFFSET} + %{DISP}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'gate_off = RAM:u16[effective_address]',
            'gate_sel = RAM:u16[effective_address + 2]',
            '${CALL_FAR_PROTECTED}',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_011_01', 'DISP_i8'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'offset = (${MOD_RM_OFFSET} + %{DISP}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_REAL}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'offset = (${MOD_RM_OFFSET} + %{DISP}):u16',
            'effective_address = ${MOD_RM_SEGMENT} + offset',
            '${SEGMENT_LIMIT_CHECK_PROTECTED16}',
            'gate_off = RAM:u16[effective_address]',
            'gate_sel = RAM:u16[effective_address + 2]',
            '${CALL_FAR_PROTECTED}',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm_011_10', 'DISP_i16'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 11,
    },
    {
      modes: {
        real: {
          operation: [
            'tmp = SP - 4',
            'stack_address = SS_BASE + tmp',
            '#GP if tmp == 0xffff',
            '#GP if (tmp + 2) == 0xffff',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'SP = tmp',
            'effective_address = ${MOD_RM_RM16}',
            'IP = RAM:u16[effective_address]',
            'CS = RAM:u16[effective_address + 2]',
          ],
        },
        protected: {
          operation: [
            'effective_address = ${MOD_RM_RM16}',
            'gate_off = RAM:u16[effective_address]',
            'gate_sel = RAM:u16[effective_address + 2]',
            '${CALL_FAR_PROTECTED}',
          ],
        },
      },
      opcode: [Opcodes.CALL_JMP_INC_DEC_PUSH, 'ModRM_rm16_011_11'],
      operands: ['rm'],
      operandSize: 16,
      distance: 'far',
      addressing: 'absolute',
      cycles: 7,
    },
  ],
};
