import type { InstructionInfo } from '@machinery/core';

import { Opcodes } from '../opcodes';

export const rcr: InstructionInfo = {
  identifier: 'rcr',
  name: 'Rotate Carry Right',
  description: '',
  modifies: ['CF'],
  undefined: ['OF'],
  macros: {
    ALU8_OP: [
      '${RESOLVE_CF}',
      'tmp_a = (tmp_a << 1) | CARRY',
      'tmp = tmp_a ~>[9] tmp_b',
      'CARRY = tmp & 0x1',
      'CF = CARRY',
      'tmp = tmp >> 1',
      'OF = ((tmp >> 7) & 0x1) ^ CARRY',
      'flag_op = flag_op | ${FLAG_OP_NOCF} | ${FLAG_OP_NOOF}',
    ],
    ALU16_OP: [
      '${RESOLVE_CF}',
      'tmp_a = (tmp_a << 1) | CARRY',
      'tmp = tmp_a ~>[17] tmp_b',
      'CARRY = tmp & 0x1',
      'CF = CARRY',
      'tmp = tmp >> 1',
      'OF = ((tmp >> 15) & 0x1) ^ CARRY',
      'flag_op = flag_op | ${FLAG_OP_NOCF} | ${FLAG_OP_NOOF}',
    ],
  },
  locals: [
    {
      identifier: 'effective_address',
      name: 'Effective Address',
      size: 32,
    },
    {
      identifier: 'tmp',
      name: 'Temporary Shift Result',
      size: 32,
    },
    {
      identifier: 'tmp_a',
      name: 'Temporary Shift Value',
      size: 32,
    },
    {
      identifier: 'tmp_b',
      name: 'Temporary Shift Amount',
      size: 8,
    },
  ],
  forms: [
    // 0xD0 /3 - RCR eb, 1
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = 1',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB,
        'ModRM_110_011_00',
        'DISP_i16',
      ],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = 1',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB, 'ModRM_rm_011_00'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = 1',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB,
        'ModRM_rm_011_01',
        'DISP_i8',
      ],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = 1',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB,
        'ModRM_rm_011_10',
        'DISP_i16',
      ],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        'tmp_a = ${MOD_RM_RM8}',
        'tmp_b = 1',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB, 'ModRM_rm_011_11'],
      operandSize: 8,
      cycles: 2,
    },
    // 0xD2 /3 - RCR eb, CL
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 9',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL,
        'ModRM_110_011_00',
        'DISP_i16',
      ],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 9',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u8[effective_address]',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL, 'ModRM_rm_011_00'],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 9',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL,
        'ModRM_rm_011_01',
        'DISP_i8',
      ],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 9',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL,
        'ModRM_rm_011_10',
        'DISP_i16',
      ],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 9',
        'next if tmp_b == 0',
        'tmp_a = ${MOD_RM_RM8}',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = tmp',
      ],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL, 'ModRM_rm_011_11'],
      operandSize: 8,
      cycles: 5,
    },
    // 0xC0 /3 - RCR eb, db
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 9',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_110_011_00',
        'DISP_i16',
        'IMM_u8',
      ],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 9',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u8[effective_address]',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_rm_011_00',
        'IMM_u8',
      ],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 9',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_rm_011_01',
        'DISP_i8',
        'IMM_u8',
      ],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 9',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_rm_011_10',
        'DISP_i16',
        'IMM_u8',
      ],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 9',
        'next if tmp_b == 0',
        'tmp_a = ${MOD_RM_RM8}',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_rm_011_11',
        'IMM_u8',
      ],
      operandSize: 8,
      cycles: 5,
    },
    // 0xD1 /3 - RCR ew, 1
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = 1',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW,
        'ModRM_110_011_00',
        'DISP_i16',
      ],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = 1',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW, 'ModRM_rm_011_00'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = 1',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW,
        'ModRM_rm_011_01',
        'DISP_i8',
      ],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = 1',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW,
        'ModRM_rm_011_10',
        'DISP_i16',
      ],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        'tmp_a = ${MOD_RM_RM16}',
        'tmp_b = 1',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW, 'ModRM_rm_011_11'],
      operandSize: 16,
      cycles: 2,
    },
    // 0xD3 /3 - RCR ew, CL
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 17',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL,
        'ModRM_110_011_00',
        'DISP_i16',
      ],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 17',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u16[effective_address]',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL, 'ModRM_rm_011_00'],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 17',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL,
        'ModRM_rm_011_01',
        'DISP_i8',
      ],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 17',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL,
        'ModRM_rm_011_10',
        'DISP_i16',
      ],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (CL & 0x1f) % 17',
        'next if tmp_b == 0',
        'tmp_a = ${MOD_RM_RM16}',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = tmp',
      ],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL, 'ModRM_rm_011_11'],
      operandSize: 16,
      cycles: 5,
    },
    // 0xC1 /3 - RCR ew, db
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 17',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_110_011_00',
        'DISP_i16',
        'IMM_u8',
      ],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 17',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u16[effective_address]',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_rm_011_00',
        'IMM_u8',
      ],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 17',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_rm_011_01',
        'DISP_i8',
        'IMM_u8',
      ],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 17',
        'next if tmp_b == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_rm_011_10',
        'DISP_i16',
        'IMM_u8',
      ],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'tmp_b = (%{IMM} & 0x1f) % 17',
        'next if tmp_b == 0',
        'tmp_a = ${MOD_RM_RM16}',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_rm_011_11',
        'IMM_u8',
      ],
      operandSize: 16,
      cycles: 5,
    },
  ],
};
