import type { InstructionInfo } from '@machinery/core';

import { Opcodes } from '../opcodes';

export const rol: InstructionInfo = {
  identifier: 'rol',
  name: 'Rotate Left',
  description: '',
  modifies: ['CF'],
  undefined: ['OF'],
  macros: {
    ALU8_OP: [
      'tmp = tmp_a <~[8] tmp_b',
      'CARRY = (tmp_b % 8) == 0 ? CARRY : (tmp_a >> (8 - tmp_b)) & 0x1',
      'CF = CARRY',
      'OF = (((tmp_a >> 6) - 1) & 0x3) < 2 ? 1 : 0',
      'flag_op = flag_op | ${FLAG_OP_NOCF} | ${FLAG_OP_NOOF}',
    ],
    ALU16_OP: [
      'tmp = tmp_a <~[16] tmp_b',
      'CARRY = (tmp_b % 16) == 0 ? CARRY : (tmp_a >> (16 - tmp_b)) & 0x1',
      'CF = CARRY',
      'OF = (((tmp_a >> 14) - 1) & 0x3) < 2 ? 1 : 0',
      'flag_op = flag_op | ${FLAG_OP_NOCF} | ${FLAG_OP_NOOF}',
    ],
  },
  locals: [
    {
      identifier: 'effective_address',
      name: 'Effective Address',
      size: 32,
    },
    {
      identifier: 'tmp',
      name: 'Temporary Shift Result',
      size: 32,
    },
    {
      identifier: 'tmp_a',
      name: 'Temporary Shift Value',
      size: 32,
    },
    {
      identifier: 'tmp_b',
      name: 'Temporary Shift Amount',
      size: 8,
    },
  ],
  forms: [
    // 0xD0 /0 - ROL eb, 1
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = 1',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB,
        'ModRM_110_000_00',
        'DISP_i16',
      ],
      operands: ['rm'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = 1',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB, 'ModRM_rm_000_00'],
      operands: ['rm'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = 1',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB,
        'ModRM_rm_000_01',
        'DISP_i8',
      ],
      operands: ['rm'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = 1',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB,
        'ModRM_rm_000_10',
        'DISP_i16',
      ],
      operands: ['rm'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        'tmp_a = ${MOD_RM_RM8}',
        'tmp_b = 1',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = tmp',
      ],
      modifies: ['OF', 'CF'],
      undefined: [],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB, 'ModRM_rm8_000_11'],
      operands: ['rm'],
      operandSize: 8,
      cycles: 2,
    },
    // 0xD2 /0 - ROL eb, CL
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = CL & 0x1f',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL,
        'ModRM_110_000_00',
        'DISP_i16',
      ],
      operands: ['rm'],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = CL & 0x1f',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL, 'ModRM_rm_000_00'],
      operands: ['rm'],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = CL & 0x1f',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL,
        'ModRM_rm_000_01',
        'DISP_i8',
      ],
      operands: ['rm'],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = CL & 0x1f',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL,
        'ModRM_rm_000_10',
        'DISP_i16',
      ],
      operands: ['rm'],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'tmp_a = ${MOD_RM_RM8}',
        'tmp_b = CL & 0x1f',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = tmp',
      ],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_CL, 'ModRM_rm8_000_11'],
      operands: ['rm'],
      operandSize: 8,
      cycles: 5,
    },
    // 0xC0 /0 - ROL eb, db
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_110_000_00',
        'DISP_i16',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_rm_000_00',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_rm_000_01',
        'DISP_i8',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u8[effective_address]',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_rm_000_10',
        'DISP_i16',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 8,
      cycles: 8,
    },
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'tmp_a = ${MOD_RM_RM8}',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EB_DB,
        'ModRM_rm8_000_11',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 8,
      cycles: 5,
    },
    // 0xD1 /0 - ROL ew, 1
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = 1',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW,
        'ModRM_110_000_00',
        'DISP_i16',
      ],
      operands: ['rm'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = 1',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW, 'ModRM_rm_000_00'],
      operands: ['rm'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = 1',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW,
        'ModRM_rm_000_01',
        'DISP_i8',
      ],
      operands: ['rm'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = 1',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW,
        'ModRM_rm_000_10',
        'DISP_i16',
      ],
      operands: ['rm'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        'tmp_a = ${MOD_RM_RM16}',
        'tmp_b = 1',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = tmp',
      ],
      modifies: ['OF', 'CF', 'ZF', 'PF', 'SF'],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW, 'ModRM_rm16_000_11'],
      operands: ['rm'],
      operandSize: 16,
      cycles: 2,
    },
    // 0xD3 /0 - ROL ew, CL
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = CL & 0x1f',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL,
        'ModRM_110_000_00',
        'DISP_i16',
      ],
      operands: ['rm'],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = CL & 0x1f',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL, 'ModRM_rm_000_00'],
      operands: ['rm'],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = CL & 0x1f',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL,
        'ModRM_rm_000_01',
        'DISP_i8',
      ],
      operands: ['rm'],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = CL & 0x1f',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL,
        'ModRM_rm_000_10',
        'DISP_i16',
      ],
      operands: ['rm'],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'next if (CL & 0x1f) == 0',
        'tmp_a = ${MOD_RM_RM16}',
        'tmp_b = CL & 0x1f',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = tmp',
      ],
      opcode: [Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_CL, 'ModRM_rm16_000_11'],
      operands: ['rm'],
      operandSize: 16,
      cycles: 5,
    },
    // 0xC1 /0 - ROL ew, db
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_110_000_00',
        'DISP_i16',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_rm_000_00',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_rm_000_01',
        'DISP_i8',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'tmp_a = RAM:u16[effective_address]',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_rm_000_10',
        'DISP_i16',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 16,
      cycles: 8,
    },
    {
      operation: [
        'next if (%{IMM} & 0x1f) == 0',
        'tmp_a = ${MOD_RM_RM16}',
        'tmp_b = %{IMM} & 0x1f',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = tmp',
      ],
      opcode: [
        Opcodes.ROL_ROR_RCL_RCR_SAL_SAR_SHR_EW_DB,
        'ModRM_rm16_000_11',
        'IMM_u8',
      ],
      operands: ['rm', 'imm'],
      operandSize: 16,
      cycles: 5,
    },
  ],
};
