import type { InstructionInfo } from '@machinery/core';

import { Opcodes } from '../opcodes';

// TODO: #13 with offset of 0xffff
export const sbb: InstructionInfo = {
  identifier: 'sbb',
  name: 'Integer Subtraction with Borrow',
  description:
    'The second operand is added to the carry flag and the result is subtracted from the first operand. The first operand is replaced with the result of the subtraction, and the flags are set accordingly.\n\nWhen a byte-immediate value is subtracted from a word operand, the immediate value is first sign-extended.',
  modifies: ['OF', 'SF', 'ZF', 'AF', 'PF', 'CF'],
  undefined: [],
  macros: {
    ALU8_OP: [
      'alu_result = a - (b + CARRY)',
      'flag_op = ${FLAG_OP_ALU} | ${FLAG_OP_SUB} | CARRY | ${FLAG_OP_8BIT}',
    ],
    ALU16_OP: [
      'alu_result = a - (b + CARRY)',
      'flag_op = ${FLAG_OP_ALU} | ${FLAG_OP_SUB} | CARRY | ${FLAG_OP_16BIT}',
    ],
  },
  locals: [
    {
      identifier: 'effective_address',
      name: 'Effective Address',
      size: 32,
    },
  ],
  forms: [
    // 0x18 /r - SBB eb, rb
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.SBB_EB_RB, 'ModRM_110_reg_00', 'DISP_i16'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u8[effective_address]',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.SBB_EB_RB, 'ModRM_rm_reg_00'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.SBB_EB_RB, 'ModRM_rm_reg_01', 'DISP_i8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.SBB_EB_RB, 'ModRM_rm_reg_10', 'DISP_i16'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM8}',
        'b = ${MOD_RM_REG8}',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = alu_result',
      ],
      opcode: [Opcodes.SBB_EB_RB, 'ModRM_rm_reg_11'],
      operandSize: 8,
      cycles: 2,
    },
    // 0x19 /r - SBB ew, rw
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.SBB_EW_RW, 'ModRM_110_reg_00', 'DISP_i16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u16[effective_address]',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.SBB_EW_RW, 'ModRM_rm_reg_00'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.SBB_EW_RW, 'ModRM_rm_reg_01', 'DISP_i8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.SBB_EW_RW, 'ModRM_rm_reg_10', 'DISP_i16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM16}',
        'b = ${MOD_RM_REG16}',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = alu_result',
      ],
      opcode: [Opcodes.SBB_EW_RW, 'ModRM_rm_reg_11'],
      operandSize: 16,
      cycles: 2,
    },
    // 0x1A /r - SBB rb, eb
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = ${MOD_RM_REG8}',
        'b = RAM:u8[effective_address]',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.SBB_RB_EB, 'ModRM_110_reg_00', 'DISP_i16'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = ${MOD_RM_REG8}',
        'b = RAM:u8[effective_address]',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.SBB_RB_EB, 'ModRM_rm_reg_00'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = ${MOD_RM_REG8}',
        'b = RAM:u8[effective_address]',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.SBB_RB_EB, 'ModRM_rm_reg_01', 'DISP_i8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = ${MOD_RM_REG8}',
        'b = RAM:u8[effective_address]',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.SBB_RB_EB, 'ModRM_rm_reg_10', 'DISP_i16'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_REG8}',
        'b = ${MOD_RM_RM8}',
        '${ALU8_OP}',
        '${MOD_RM_REG8} = alu_result',
      ],
      opcode: [Opcodes.SBB_RB_EB, 'ModRM_rm_reg_11'],
      operandSize: 8,
      cycles: 2,
    },
    // 0x1B /r - SBB rw, ew
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = ${MOD_RM_REG16}',
        'b = RAM:u16[effective_address]',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.SBB_RW_EW, 'ModRM_110_reg_00', 'DISP_i16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = ${MOD_RM_REG16}',
        'b = RAM:u16[effective_address]',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.SBB_RW_EW, 'ModRM_rm_reg_00'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = ${MOD_RM_REG16}',
        'b = RAM:u16[effective_address]',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.SBB_RW_EW, 'ModRM_rm_reg_01', 'DISP_i8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = ${MOD_RM_REG16}',
        'b = RAM:u16[effective_address]',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.SBB_RW_EW, 'ModRM_rm_reg_10', 'DISP_i16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_REG16}',
        'b = ${MOD_RM_RM16}',
        '${ALU16_OP}',
        '${MOD_RM_REG16} = alu_result',
      ],
      opcode: [Opcodes.SBB_RW_EW, 'ModRM_rm_reg_11'],
      operandSize: 16,
      cycles: 2,
    },
    // 0x1C db - SBB AL, db
    {
      operation: [
        '${RESOLVE_CF}',
        'a = AL',
        'b = %{IMM}',
        '${ALU8_OP}',
        'AL = alu_result',
      ],
      opcode: [Opcodes.SBB_AL_DB, 'IMM_u8'],
      operandSize: 8,
      cycles: 3,
    },
    // 0x1D dw - SBB AX, dw
    {
      operation: [
        '${RESOLVE_CF}',
        'a = AX',
        'b = %{IMM}',
        '${ALU16_OP}',
        'AX = alu_result',
      ],
      opcode: [Opcodes.SBB_AX_DW, 'IMM_u16'],
      operandSize: 16,
      cycles: 3,
    },
    // 0x80 /3 db - SBB eb, db
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = %{IMM}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_110_011_00', 'DISP_i16', 'IMM_u8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u8[effective_address]',
        'b = %{IMM}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_rm_011_00', 'IMM_u8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = %{IMM}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_rm_011_01', 'DISP_i8', 'IMM_u8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u8[effective_address]',
        'b = %{IMM}',
        '${ALU8_OP}',
        'RAM:u8[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_rm_011_10', 'DISP_i16', 'IMM_u8'],
      operandSize: 8,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM8}',
        'b = %{IMM}',
        '${ALU8_OP}',
        '${MOD_RM_RM8} = alu_result',
      ],
      opcode: [Opcodes.ALU_EB_DB, 'ModRM_rm_011_11', 'IMM_u8'],
      operandSize: 8,
      cycles: 3,
    },
    // 0x81 /3 dw - SBB ew, dw
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_110_011_00', 'DISP_i16', 'IMM_u16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_rm_011_00', 'IMM_u16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_rm_011_01', 'DISP_i8', 'IMM_u16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_rm_011_10', 'DISP_i16', 'IMM_u16'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM16}',
        'b = %{IMM}',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DW, 'ModRM_rm_011_11', 'IMM_u16'],
      operandSize: 16,
      cycles: 3,
    },
    // 0x83 /3 db - SBB ew, db
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_110_011_00', 'DISP_i16', 'IMM_i8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_rm_011_00', 'IMM_i8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_rm_011_01', 'DISP_i8', 'IMM_i8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'effective_address = ${MOD_RM_SEGMENT} + ${MOD_RM_OFFSET} + %{DISP}',
        'a = RAM:u16[effective_address]',
        'b = %{IMM}',
        '${ALU16_OP}',
        'RAM:u16[effective_address] = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_rm_011_10', 'DISP_i16', 'IMM_i8'],
      operandSize: 16,
      cycles: 7,
    },
    {
      operation: [
        '${RESOLVE_CF}',
        'a = ${MOD_RM_RM16}',
        'b = %{IMM}',
        '${ALU16_OP}',
        '${MOD_RM_RM16} = alu_result',
      ],
      opcode: [Opcodes.ALU_EW_DB, 'ModRM_rm_011_11', 'IMM_i8'],
      operandSize: 16,
      cycles: 3,
    },
  ],
};
