import type { ModeInfo } from '@machinery/core';

import TypeScriptBackend from './TypeScriptBackend';

import type { LocalMap } from '../types';

/**
 * Backend that generates a TypeScript WasmMachine wrapper class.
 *
 * The wrapper exposes the same register getters/setters as the TS Machine
 * (since they share the same WebAssembly.Memory layout), but delegates
 * decode/reset to a compiled WebAssembly module for execution speed.
 */
class WasmMachineBackend extends TypeScriptBackend {
  prologue(): string[] {
    const code: string[] = [];

    code.push('// This file is generated by @machinery/virtual-machine');
    code.push('/* eslint-disable */');
    code.push('');
    code.push('export default class WasmMachine {');
    code.push(
      `  static readonly RAM_OFFSET = 0x${this.linearStart.toString(16)};`,
    );
    code.push('  memory: WebAssembly.Memory;');
    code.push('  mem8: Uint8Array;');
    code.push('  mem16: Uint16Array;');
    code.push('  mem32: Uint32Array;');
    code.push('  private instance!: WebAssembly.Instance;');
    code.push('');

    // Constructor — sets up shared memory but does NOT instantiate wasm
    code.push('  constructor() {');
    code.push(
      '    this.memory = new WebAssembly.Memory({ initial: 30, maximum: 1024 });',
    );
    code.push('    this.mem8 = new Uint8Array(this.memory.buffer);');
    code.push('    this.mem16 = new Uint16Array(this.memory.buffer);');
    code.push('    this.mem32 = new Uint32Array(this.memory.buffer);');
    code.push('    this.mode = 0;');
    code.push('  }');
    code.push('');

    // Static factory — creates and initializes the machine
    code.push(
      '  static async create(wasm: BufferSource): Promise<WasmMachine> {',
    );
    code.push('    const machine = new WasmMachine();');
    code.push('    await machine.init(wasm);');
    code.push('    return machine;');
    code.push('  }');
    code.push('');

    // init() — instantiates the wasm module with shared memory
    code.push('  async init(wasm: BufferSource) {');
    code.push('    const { instance } = await WebAssembly.instantiate(wasm, {');
    code.push('      env: {');
    code.push('        memory: this.memory,');
    for (const memoryInfo of this.target.memory || []) {
      if (memoryInfo.type === 'programmable') {
        code.push(
          `  ${memoryInfo.identifier}_read: (size: number, address: number) => this.${memoryInfo.identifier}_read(size, address),`,
        );
        code.push(
          `  ${memoryInfo.identifier}_write: (size: number, address: number, value: number) => this.${memoryInfo.identifier}_write(size, address, value),`,
        );
      }
    }
    ((this.target.modes as Pick<ModeInfo, 'identifier'>[]) || [])
      .concat(
        this.target.modes?.find(
          (modeInfo) => modeInfo.identifier === 'default',
        ) === undefined
          ? [{ identifier: 'default' }]
          : [],
      )
      .forEach((modeInfo) => {
        const mode = modeInfo.identifier;
        code.push(
          `        interrupt_${mode}: (vector: number) => this.interrupt_${mode}(vector),`,
        );
      });
    code.push('      },');
    code.push('    });');
    code.push('    this.instance = instance;');
    code.push('    (this.instance.exports.reset as Function)();');
    code.push('  }');
    code.push('');

    // reset() — delegates to wasm
    code.push('  reset() {');
    code.push('    (this.instance.exports.reset as Function)();');
    code.push('  }');
    code.push('');

    // interrupt_<mode>() — overridable callback, returns 1 (handled) by default
    // The wasm module calls this; if it returns 0, wasm does default handler vectoring.
    ((this.target.modes as Pick<ModeInfo, 'identifier'>[]) || [])
      .concat(
        this.target.modes?.find(
          (modeInfo) => modeInfo.identifier === 'default',
        ) === undefined
          ? [{ identifier: 'default' }]
          : [],
      )
      .forEach((modeInfo) => {
        const mode = modeInfo.identifier;
        code.push(`  interrupt_${mode}(_: number): number {`);
        code.push('    return 0;');
        code.push('  }');
        code.push('');
      });

    // Create functions for accessing programmable memory
    for (const memoryInfo of this.target.memory || []) {
      if (memoryInfo.type === 'programmable') {
        code.push(
          `  ${memoryInfo.identifier}_read(size: number, _address: number): number {`,
        );
        code.push('    if (size === 32) {');
        code.push(
          `    return 0x${((((memoryInfo.default || 0x0) << 24) | ((memoryInfo.default || 0x0) << 16) | ((memoryInfo.default || 0x0) << 8) | (memoryInfo.default || 0x0)) >>> 0).toString(16)};`,
        );
        code.push('    }');
        code.push('    else if (size === 16) {');
        code.push(
          `    return 0x${(((memoryInfo.default || 0x0) << 8) | (memoryInfo.default || 0x0)).toString(16)};`,
        );
        code.push('    }');
        code.push(`    return 0x${(memoryInfo.default || 0x0).toString(16)};`);
        code.push(`  }`);
        code.push('');
        code.push(
          `  ${memoryInfo.identifier}_write(_size: number, _address: number, _value: number) {`,
        );
        code.push(`  }`);
        code.push('');
      }
    }

    // Create functions for accessing system state
    const generatedDummy = {
      accesses: [],
      modifies: [],
      code: [],
      context: {
        mode: 'default',
        locals: {},
        localMap: { _ip: { identifier: '_ip' } },
      },
    };
    if (this.parsed.system.mode) {
      code.push(`  get mode(): number {`);
      code.push(
        `    return ${this.readMemory(generatedDummy, this.parsed.system.mode, this.parsed.system.mode.address)};`,
      );
      code.push(`  }`);
      code.push('');
      code.push(`  set mode(value: number) {`);
      code.push(
        `    ${this.writeMemory(generatedDummy, this.parsed.system.mode, this.parsed.system.mode.address, 'value')};`,
      );
      code.push(`  }`);
      code.push('');
    }

    // Register getters/setters — reuse the TypeScriptBackend logic
    // (these just read/write from shared WebAssembly.Memory)
    const registerCode = this.generateRegisterAccessors();
    for (const line of registerCode) {
      code.push(line);
    }

    return code;
  }

  /**
   * Generate register getter/setter code — extracted from TypeScriptBackend.prologue().
   */
  private generateRegisterAccessors(): string[] {
    const target = this.target;
    const code: string[] = [];

    for (const info of target.registers) {
      const name = info.identifier;
      const parsedRegister = this.parsed.registers[name];
      const getModes = Object.keys(parsedRegister?.get || {});
      const getOnlyDefault =
        getModes.length === 0 ||
        (getModes.length === 1 && getModes[0] === 'default');

      // Getter
      const jsN = name.replace(/'/g, '_');
      code.push(`  get ${jsN}() {`);
      ((target.modes as { identifier: string }[]) || [])
        .concat([{ identifier: 'default' }])
        .forEach((modeInfo, i) => {
          const mode = modeInfo.identifier;
          if (mode !== 'default' && getModes.includes(mode)) {
            code.push(`    ${i !== 0 ? 'else ' : ''}if (this.mode === ${i}) {`);
          } else if (mode === 'default' && !getOnlyDefault) {
            code.push('    else { // default');
          }
          if (getModes.includes(mode) || mode === 'default') {
            const { localMap }: { localMap: LocalMap } = parsedRegister?.get?.[
              mode
            ] || { localMap: {} };
            for (const [localName, localInfo] of Object.entries(localMap)) {
              if (localName === 'vector') {
                continue;
              }
              code.push(`      let ${localInfo.identifier} = 0;`);
            }
            const generated = {
              accesses: [name],
              modifies: [] as string[],
              code: [] as string[],
              context: {
                mode,
                locals: {},
                localMap: { _ip: { identifier: '_ip' } },
                suppressRaise: true,
              },
            };
            const readCode = this.readRegister(generated, {
              type: 'register' as const,
              identifier: name,
              mapping: this.registerMap.registers[name],
              size: this.registerMap.registers[name].size,
            });
            for (const line of this.fromAccessors(generated)) {
              code.push(`    ${getOnlyDefault ? '' : '  '}${line};`);
            }
            for (const line of readCode.slice(0, readCode.length - 1)) {
              code.push(`    ${getOnlyDefault ? '' : '  '}${line};`);
            }
            code.push(
              `    ${getOnlyDefault ? '' : '  '}return ${readCode[readCode.length - 1]};`,
            );
            if (!getOnlyDefault) {
              code.push(`    }`);
            }
          }
        });
      code.push('  }');
      code.push('');

      // Setter
      const setModes = Object.keys(parsedRegister?.set || {});
      const setOnlyDefault =
        setModes.length === 0 ||
        (setModes.length === 1 && setModes[0] === 'default');
      code.push(`  set ${jsN}(value: number) {`);
      ((target.modes as { identifier: string }[]) || [])
        .concat([{ identifier: 'default' }])
        .forEach((modeInfo, i) => {
          const mode = modeInfo.identifier;
          if (mode !== 'default' && setModes.includes(mode)) {
            code.push(`    ${i !== 0 ? 'else ' : ''}if (this.mode === ${i}) {`);
          } else if (mode === 'default' && !setOnlyDefault) {
            code.push('    else { // default');
          }
          if (setModes.includes(mode) || mode === 'default') {
            const { localMap }: { localMap: LocalMap } = parsedRegister?.set?.[
              mode
            ] || { localMap: {} };
            for (const [localName, localInfo] of Object.entries(localMap)) {
              if (localName === 'vector') {
                continue;
              }
              code.push(`      let ${localInfo.identifier} = 0;`);
            }
            const generated2 = {
              accesses: [] as string[],
              modifies: [name],
              code: [] as string[],
              context: {
                mode,
                locals: {},
                localMap: { _ip: { identifier: '_ip' } },
                suppressRaise: true,
              },
            };
            const writeCode = this.writeRegister(
              generated2,
              {
                type: 'register' as const,
                identifier: name,
                mapping: this.registerMap.registers[name],
                size: this.registerMap.registers[name].size,
              },
              'value',
            );
            for (const line of writeCode) {
              code.push(`    ${setOnlyDefault ? '' : '  '}${line};`);
            }
            for (const line of this.fromModifies(generated2)) {
              code.push(`    ${setOnlyDefault ? '' : '  '}${line};`);
            }
            if (!setOnlyDefault) {
              code.push(`    }`);
            }
          }
        });
      code.push('  }');
      code.push('');

      // Sub-field accessors (e.g., AL from AX)
      for (const subinfo of info.fields || []) {
        if (!subinfo.global) {
          continue;
        }
        const subname = subinfo.identifier;
        const subJs = subname.replace(/'/g, '_');
        const generated3 = {
          accesses: [] as string[],
          modifies: [] as string[],
          code: [] as string[],
          context: {
            mode: this.target.modes?.[0]?.identifier || 'default',
            locals: {},
            localMap: { _ip: { identifier: '_ip' } },
            suppressRaise: true,
          },
        };
        code.push('  get ' + subJs + '() {');
        for (const line of this.fromAccessors(generated3)) {
          code.push(`    ${line};`);
        }
        const readSubCode = this.readRegister(generated3, {
          type: 'register' as const,
          identifier: subname,
          mapping: this.registerMap.registers[subname],
          size: this.registerMap.registers[subname].size,
        });
        for (const line of readSubCode.slice(0, readSubCode.length - 1)) {
          code.push(`    ${line};`);
        }
        code.push('    return ' + readSubCode[readSubCode.length - 1] + ';');
        code.push('  }');
        code.push('');
        const writeSubCode = this.writeRegister(
          generated3,
          {
            type: 'register' as const,
            identifier: subname,
            mapping: this.registerMap.registers[subname],
            size: this.registerMap.registers[subname].size,
          },
          'value',
        );
        code.push('  set ' + subJs + '(value: number) {');
        for (const line of writeSubCode) {
          code.push(`    ${line};`);
        }
        for (const line of this.fromModifies(generated3)) {
          code.push(`    ${line};`);
        }
        code.push('  }');
        code.push('');
      }
    }

    return code;
  }

  /**
   * Generate decoder methods that delegate to wasm exports.
   */
  buildDecoder(mode: string): string[] {
    return [
      `  decode_${mode}() {`,
      `    (this.instance.exports.decode_${mode} as Function)();`,
      `  }`,
    ];
  }

  epilogue(): string[] {
    return ['}'];
  }
}

export default WasmMachineBackend;
