import type {
  InstructionForm,
  InstructionFormFlat,
  InstructionFormModes,
  InstructionInfo,
  ModeInfo,
  OpcodeMatcher,
  OpcodeMatcherField,
} from '@machinery/core';

import {
  BinaryExpressionNode,
  BinaryLogicNode,
  ComparisonEvaluationNode,
  ComparisonNode,
  ExpressionNode,
  LocalOperandNode,
  Node,
  OperandNode,
  NextIfNode,
  IfBlockNode,
  LoopBlockNode,
  LoopIfNode,
  TernaryExpressionNode,
  UnaryExpressionNode,
} from '../ast';
import Backend from '../Backend';
import type {
  DecoderMap,
  ExpressionType,
  InputMap,
  GeneratedStatement,
  MemoryReference,
  RegisterReference,
  LocalReference,
  LocalsInfo,
} from '../types';

interface PrefixMapEntry {
  instruction: InstructionInfo;
  variant: number;
}

interface DecoderContext {
  /** The mode we are decoding */
  mode: string;
  /** The decoder code */
  code: string[];
  /** Any variables used within instruction operation */
  variables: string[];
  /** The maximum number of bytes the decoder will ever read on one pass */
  bytesCount: number;
  /** The prefix count */
  prefixCount: number;
  /** A mapping of known prefixes to instruction form information. */
  prefixMap: PrefixMapEntry[];
  /** Block label counter for unique br_table labels */
  labelCounter: number;
}

/** Sanitize an identifier for use as a WAT name (e.g. AF' → AF_) */
function watName(name: string): string {
  return name.replace(/'/g, '_');
}

class WebAssemblyBackend extends Backend {
  applyCoercion(result: string[], coercion: string): string[] {
    const size = parseInt(coercion.slice(1));
    const last = result[result.length - 1];
    if (coercion.startsWith('i')) {
      result[result.length - 1] = this.signExtend(last, size);
    } else {
      const mask = (Math.pow(2, size) - 1) >>> 0;
      result[result.length - 1] = `(i32.and ${last} (i32.const ${mask}))`;
    }
    return result;
  }

  /** Emit wasm sign-extension from `bits` to i32 */
  private signExtend(expr: string, bits: number): string {
    if (bits === 8) return `(i32.extend8_s ${expr})`;
    if (bits === 16) return `(i32.extend16_s ${expr})`;
    if (bits >= 32) return expr;
    return `(i32.shr_s (i32.shl ${expr} (i32.const ${32 - bits})) (i32.const ${32 - bits}))`;
  }

  /** Track which register names map to which wasm locals */
  private registerLocals: Map<string, { local: string; size: number }> =
    new Map();
  /** Track state/ALU locals */
  private stateLocals: Map<string, { local: string; size: number }> = new Map();

  prologue(): string[] {
    const code: string[] = [];

    code.push(';; This file is generated by @machinery/virtual-machine');
    code.push('(module');

    // Import shared memory from host
    code.push('  ;; Import shared memory from host');
    code.push('  (import "env" "memory" (memory 30 1024))');
    for (const memoryInfo of this.target.memory || []) {
      if (memoryInfo.type === 'programmable') {
        code.push(
          `  (import "env" "${memoryInfo.identifier}_read" (func $${memoryInfo.identifier}_read (param i32) (param i32) (result i32)))`,
          `  (import "env" "${memoryInfo.identifier}_write" (func $${memoryInfo.identifier}_write (param i32) (param i32) (param i32) (result i32)))`,
        );
      }
    }
    code.push('');

    // Import interrupt callback (returns i32: 1=handled by host, 0=vector through IVT)
    code.push('  ;; Import interrupt callback(s) from host');
    ((this.target.modes as Pick<ModeInfo, 'identifier'>[]) || [])
      .concat(
        this.target.modes?.find(
          (modeInfo) => modeInfo.identifier === 'default',
        ) === undefined
          ? [{ identifier: 'default' }]
          : [],
      )
      .forEach((modeInfo) => {
        const mode = modeInfo.identifier;
        code.push(
          `  (import "env" "interrupt_${mode}" (func $interrupt_${mode} (param i32) (result i32)))`,
        );
      });
    code.push('');

    // Build register local mapping
    this.buildRegisterLocals();

    // --- reset function ---
    code.push('  ;; Reset all registers to initial values');
    code.push('  (func $reset (export "reset")');
    // Zero the register space
    const regSize = this.registerMap.size;
    // Use memory.fill if available, otherwise byte-by-byte
    for (let i = 0; i < regSize; i += 4) {
      code.push(`    (i32.store (i32.const ${i}) (i32.const 0))`);
    }
    // Initialize registers with non-zero initial values
    for (const [name, info] of Object.entries(
      this.registerMap.registers || {},
    )) {
      if (info.initialValue === undefined || info.initialValue === 0) {
        continue;
      }
      let size = info.size;
      if (size <= 8) size = 8;
      else if (size <= 16) size = 16;
      else size = 32;
      const storeOp =
        size === 8 ? 'i32.store8' : size === 16 ? 'i32.store16' : 'i32.store';
      const byteOffset =
        size === 8 ? info.index : size === 16 ? info.index * 2 : info.index * 4;
      code.push(`    ;; ${name} = 0x${info.initialValue.toString(16)}`);
      code.push(
        `    (${storeOp} (i32.const ${byteOffset}) (i32.const ${info.initialValue}))`,
      );
    }
    // Initialize ROM
    for (const [name, info] of Object.entries(this.memoryMap || {})) {
      if (!info.data || info.data.length === 0) {
        continue;
      }
      code.push(`    ;; ${name}`);
      const data = Array.from(info.data);
      // Store ROM data element by element
      const bytes = info.size / 8;
      for (let i = 0; i < data.length; i++) {
        if (data[i] !== 0) {
          code.push(
            `    (i32.store${info.size} (i32.const ${info.start + i * bytes}) (i32.const 0x${data[i].toString(16)}))`,
          );
        }
      }
    }
    code.push('  )');
    code.push('');

    // Generate interrupt handler function from processor definition
    const locals: LocalsInfo = {};
    if (this.parsed.interrupts?.handler) {
      ((this.target.modes as Pick<ModeInfo, 'identifier'>[]) || [])
        .concat([{ identifier: 'default' }])
        .forEach((modeInfo) => {
          const mode = modeInfo.identifier;
          const { statement, localMap } =
            this.parsed.interrupts.handler?.[mode] || {};

          // Transpile the statement node for this instruction form
          code.push('  ;; Interrupt handler');
          if (statement && localMap) {
            const vectorId = localMap.vector?.identifier || 'vector';
            const { code: handlerCode } = this.fromStatement(statement, {
              mode: this.target.modes?.[0]?.identifier || 'default',
              locals,
              localMap,
            });
            code.push(
              `  (func $interrupt_${mode}_handler (param $${vectorId} i32)`,
            );
            for (const [localName, localInfo] of Object.entries(localMap)) {
              if (localName === 'vector') {
                continue;
              }
              code.push(`    (local $${localInfo.identifier} i32)`);
            }
            for (const line of handlerCode) {
              code.push('    ' + line);
            }
          } else {
            code.push(`  (func $interrupt_${mode}_handler (param $_ i32)`);
            code.push(`    ;; Empty handler for this mode`);
          }
          code.push('  )');
          code.push('');
        });
    }

    return code;
  }

  epilogue(): string[] {
    return [')'];
  }

  private buildRegisterLocals() {
    this.registerLocals.clear();
    this.stateLocals.clear();

    for (const [name, info] of Object.entries(
      this.registerMap.registers || {},
    )) {
      const local = `$${watName(name)}`;
      this.registerLocals.set(name, { local, size: info.size });
    }
  }

  /**
   * Get the byte offset for a register in linear memory.
   */
  private regByteOffset(name: string): number {
    const info = this.registerMap.registers[name];
    if (!info) throw new Error(`Unknown register: ${name}`);
    const size = info.size;
    if (size <= 8) return info.index;
    if (size <= 16) return info.index * 2;
    return info.index * 4;
  }

  /**
   * Get the load instruction for a register size.
   */
  private loadOp(size: number, signed?: boolean): string {
    if (size <= 8) return signed ? 'i32.load8_s' : 'i32.load8_u';
    if (size <= 16) return signed ? 'i32.load16_s' : 'i32.load16_u';
    return 'i32.load';
  }

  /**
   * Get the store instruction for a register size.
   */
  private storeOp(size: number): string {
    if (size <= 8) return 'i32.store8';
    if (size <= 16) return 'i32.store16';
    return 'i32.store';
  }

  /**
   * Emit code to load a register from linear memory.
   */
  private emitRegLoad(name: string): string {
    const info = this.registerMap.registers[name];
    if (!info) throw new Error(`Unknown register: ${name}`);
    const byteOffset = this.regByteOffset(name);
    const load = this.loadOp(info.size);

    if (info.offset !== undefined && info.length !== undefined) {
      // Bit field: load, shift, mask
      const mask = (1 << info.length) - 1;
      if (info.offset === 0) {
        return `(i32.and (${load} (i32.const ${byteOffset})) (i32.const ${mask}))`;
      }
      return `(i32.and (i32.shr_u (${load} (i32.const ${byteOffset})) (i32.const ${info.offset})) (i32.const ${mask}))`;
    }

    return `(${load} (i32.const ${byteOffset}))`;
  }

  /**
   * Emit code to store a value to a register in linear memory.
   */
  private emitRegStore(name: string, value: string): string {
    const info = this.registerMap.registers[name];
    if (!info) throw new Error(`Unknown register: ${name}`);
    const byteOffset = this.regByteOffset(name);
    const store = this.storeOp(info.size);
    const load = this.loadOp(info.size);

    if (info.offset !== undefined && info.length !== undefined) {
      // Bit field: read-modify-write
      const mask = (1 << info.length) - 1;
      const shiftedMask = mask << info.offset;
      return `(${store} (i32.const ${byteOffset}) (i32.or (i32.and (${load} (i32.const ${byteOffset})) (i32.const ${~shiftedMask & 0xffffffff})) ${info.offset === 0 ? `(i32.and ${value} (i32.const ${mask}))` : `(i32.shl (i32.and ${value} (i32.const ${mask})) (i32.const ${info.offset}))`}))`;
    }

    return `(${store} (i32.const ${byteOffset}) ${value})`;
  }

  // --- Backend method overrides ---

  fromOperand(generated: GeneratedStatement, node: OperandNode): string[] {
    if (typeof node.value === 'number') {
      return [`(i32.const ${node.value})`];
    }
    const result = super.fromOperand(generated, node);
    // Apply sign extension for locals with signed coercion (e.g., a:i8, a:i16)
    if (node instanceof LocalOperandNode && node.coercion?.startsWith('i')) {
      const bits = parseInt(node.coercion.slice(1));
      if (bits < 32) {
        return [this.signExtend(result[0], bits)];
      }
    }
    return result;
  }

  comment(message: string): string[] {
    return [`(;; ${message} ;;)`];
  }

  wrapConditional(
    indexExpr: string,
    registerIndex: number,
    code: string[],
  ): string[] {
    return [
      `(if (i32.eq ${indexExpr} (i32.const ${registerIndex})) (then`,
      ...code.map((line) => `  ${line}`),
      `))`,
    ];
  }

  raise(
    generated: GeneratedStatement,
    value: string,
    condition?: ComparisonNode,
    fault = true,
  ): string[] {
    // In register getter/setter helpers, suppress raises — returning from the
    // helper is not the same as returning from the decode function.
    if (generated.context.suppressRaise) {
      return [];
    }

    // Build IP rollback so fault frame points to the faulting instruction
    // (before any prefix bytes were consumed).
    // Only faults roll back; traps keep IP pointing past the instruction.
    let rollback = '';
    if (fault && generated.context.ipAdvance) {
      const ip =
        this.target.fetch?.effectiveRegister ||
        (Array.isArray(this.target.fetch?.register)
          ? this.target.fetch?.register?.[0]
          : this.target.fetch?.register);
      if (ip && this.registerMap.registers[ip]) {
        const ipRef: RegisterReference = {
          type: 'register',
          identifier: ip,
          mapping: this.registerMap.registers[ip],
          size: this.registerMap.registers[ip].size,
        };
        rollback =
          this.writeRegister(generated, ipRef, `(local.get $_ip_save)`)[0] +
          ' ';
      }
    }

    const hasHandler = !!this.parsed.interrupts?.handler;
    if (hasHandler) {
      // Call JS callback first; if it returns 0 (not handled), do IVT vectoring
      const call = `(if (i32.eqz (call $interrupt_${generated.context.mode} ${value})) (then (call $interrupt_${generated.context.mode}_handler ${value})))`;
      if (condition) {
        return [
          `(if ${this.fromComparison(generated, condition)[0]} (then ${rollback}${call} (return (i32.const 0))))`,
        ];
      }
      return [call, `(return (i32.const 0))`];
    }
    // No interrupt handler defined — just call JS callback (ignore return value)
    if (condition) {
      return [
        `(if ${this.fromComparison(generated, condition)[0]} (then ${rollback}(drop (call $interrupt_${generated.context.mode} ${value})) (return (i32.const 0))))`,
      ];
    }
    return [`(drop (call $interrupt ${value}))`, `(return (i32.const 0))`];
  }

  readRegister(
    _generated: GeneratedStatement,
    reference: RegisterReference,
  ): string[] {
    let { size } = reference.mapping;
    const { index, offset, length } = reference.mapping;
    const { size: destSize, signed } = reference;

    if (size <= 8) size = 8;
    else if (size <= 16) size = 16;
    else size = 32;

    const byteOffset = size === 8 ? index : size === 16 ? index * 2 : index * 4;
    // When destSize < size and signed, use unsigned load then sign-extend from destSize
    const needsPostSignExtend = signed && destSize < size;
    const load = this.loadOp(size, needsPostSignExtend ? false : signed);

    let expr = `(${load} (i32.const ${byteOffset}))`;

    if (offset !== undefined && length !== undefined) {
      const mask = (1 << length) - 1;
      if (offset > 0) {
        expr = `(i32.shr_u ${expr} (i32.const ${offset}))`;
      }
      expr = `(i32.and ${expr} (i32.const ${mask}))`;
    }

    if (destSize !== size && destSize < size) {
      expr = `(i32.and ${expr} (i32.const ${(1 << destSize) - 1}))`;
    }

    if (needsPostSignExtend) {
      // Sign-extend from destSize bits to 32 bits
      if (destSize < 32) {
        expr = this.signExtend(expr, destSize);
      }
    } else if (signed && !load.endsWith('_s')) {
      if (destSize < 32) {
        expr = this.signExtend(expr, destSize);
      }
    }

    return [expr];
  }

  readRegisters(
    generated: GeneratedStatement,
    references: RegisterReference[],
    index: ExpressionNode,
  ): string[] {
    let { size } = references[0].mapping;
    const { size: destSize, signed } = references[0];

    if (size <= 8) size = 8;
    else if (size <= 16) size = 16;
    else size = 32;

    const effective = this.fromExpression(generated, index)[0];
    const byteMultiplier = size === 8 ? 1 : size === 16 ? 2 : 4;
    const load = this.loadOp(size, signed);

    let expr = `(${load} (i32.mul ${effective} (i32.const ${byteMultiplier})))`;

    if (destSize !== size && destSize < size) {
      expr = `(i32.and ${expr} (i32.const ${(1 << destSize) - 1}))`;
    }

    return [expr];
  }

  readMemory(
    generated: GeneratedStatement,
    reference: MemoryReference,
    address: ExpressionNode,
  ): string[] {
    let { size } = reference;
    const { signed } = reference;

    if (size <= 8) size = 8;
    else if (size <= 16) size = 16;
    else size = 32;

    const effective = this.fromExpression(generated, address)[0];

    if (reference.mapping.type === 'programmable') {
      return [
        `(call $${reference.identifier}_read (i32.const ${size}) ${effective})`,
      ];
    }

    const load = this.loadOp(size, signed);

    // When aligned, `effective` is an element index (matching TypedArray conventions).
    // WASM uses byte addressing, so scale by element size for aligned accesses.
    // Unaligned accesses already use byte addresses.
    if (reference.aligned && size > 8) {
      const shift = size === 16 ? 1 : 2;
      return [`(${load} align=1 (i32.shl ${effective} (i32.const ${shift})))`];
    }
    return [`(${load} align=1 ${effective})`];
  }

  readLocal(
    _generated: GeneratedStatement,
    reference: LocalReference,
    coercion?: string,
  ): string[] {
    const result = [`(local.get $${reference.mapping.identifier})`];
    return coercion ? this.applyCoercion(result, coercion) : result;
  }

  readGlobals(
    _generated: GeneratedStatement,
    entries: (number | string)[],
    index: string,
  ): string[] {
    // For small constant arrays, emit a br_table-based lookup
    // This is complex in Wasm; for now use a linear scan approach
    // In practice these are small (< 8 entries)
    let expr = `(i32.const ${typeof entries[entries.length - 1] === 'number' ? entries[entries.length - 1] : 0})`;
    for (let i = entries.length - 2; i >= 0; i--) {
      const val =
        typeof entries[i] === 'number'
          ? `(i32.const ${entries[i]})`
          : `(i32.const 0)`;
      expr = `(if (result i32) (i32.eq ${index} (i32.const ${i})) (then ${val}) (else ${expr}))`;
    }
    return [expr];
  }

  writeRegister(
    _generated: GeneratedStatement,
    reference: RegisterReference,
    value: string,
    exprType?: ExpressionType,
  ): string[] {
    let { size, length } = reference.mapping;
    const { index, offset } = reference.mapping;

    length ||= size;
    if (size <= 8) size = 8;
    else if (size <= 16) size = 16;
    else size = 32;

    const byteOffset = size === 8 ? index : size === 16 ? index * 2 : index * 4;
    const store = this.storeOp(size);
    const load = this.loadOp(size);

    if (offset !== undefined) {
      // Bit field: read-modify-write
      const mask = (1 << length) - 1;
      const shiftedMask = mask << offset;
      const clearMask =
        ~shiftedMask & (size === 8 ? 0xff : size === 16 ? 0xffff : 0xffffffff);
      const needsMask = !this.canSkipCoercion(exprType, length, false);
      const masked = needsMask
        ? `(i32.and ${value} (i32.const ${mask}))`
        : value;
      const maskedValue =
        offset === 0 ? masked : `(i32.shl ${masked} (i32.const ${offset}))`;
      return [
        `(${store} (i32.const ${byteOffset}) (i32.or (i32.and (${load} (i32.const ${byteOffset})) (i32.const ${clearMask})) ${maskedValue}))`,
      ];
    }

    return [`(${store} (i32.const ${byteOffset}) ${value})`];
  }

  writeRegisters(
    generated: GeneratedStatement,
    references: RegisterReference[],
    index: ExpressionNode,
    value: ExpressionNode,
  ): string[] {
    let { size } = references[0].mapping;

    if (size <= 8) size = 8;
    else if (size <= 16) size = 16;
    else size = 32;

    const effective = this.fromExpression(generated, index)[0];
    const result = this.fromExpression(generated, value)[0];
    const byteMultiplier = size === 8 ? 1 : size === 16 ? 2 : 4;
    const store = this.storeOp(size);

    return [
      `(${store} (i32.mul ${effective} (i32.const ${byteMultiplier})) ${result})`,
    ];
  }

  writeMemory(
    generated: GeneratedStatement,
    reference: MemoryReference,
    address: ExpressionNode,
    value: string,
  ): string[] {
    let { size } = reference;

    if (size <= 8) size = 8;
    else if (size <= 16) size = 16;
    else size = 32;

    const effective = this.fromExpression(generated, address)[0];
    const store = this.storeOp(size);

    if (reference.aligned && size > 8) {
      const shift = size === 16 ? 1 : 2;
      return [`(${store} align=1 (i32.shl ${effective} (i32.const ${shift})) ${value})`];
    }
    return [`(${store} align=1 ${effective} ${value})`];
  }

  writeLocal(
    _generated: GeneratedStatement,
    reference: LocalReference,
    value: string,
    exprType?: ExpressionType,
  ): string[] {
    if (reference.mapping.size) {
      if (
        this.canSkipCoercion(
          exprType,
          reference.mapping.size,
          !!reference.mapping.signed,
        )
      ) {
        return [`(local.set $${reference.mapping.identifier} ${value})`];
      }
      const coercion =
        (reference.mapping.signed ? 'i' : 'u') + reference.mapping.size;
      return [
        `(local.set $${reference.mapping.identifier} ${this.applyCoercion([value], coercion)[0]})`,
      ];
    }
    return [`(local.set $${reference.mapping.identifier} ${value})`];
  }

  writeGlobals(
    _generated: GeneratedStatement,
    entries: (number | string)[],
    index: string,
    _value: string,
  ): string[] {
    // For writing to a set of globals by index, emit if-chain
    const lines: string[] = [];
    for (let i = 0; i < entries.length; i++) {
      if (typeof entries[i] === 'string') {
        lines.push(
          `(if (i32.eq ${index} (i32.const ${i})) (then ;; write ${entries[i]} ;;))`,
        );
      }
    }
    return lines;
  }

  fromNextIf(generated: GeneratedStatement, node: NextIfNode): string[] {
    return [
      `(br_if $done ${this.fromComparison(generated, node.condition)[0]})`,
    ];
  }

  fromIf(generated: GeneratedStatement, node: IfBlockNode): string[] {
    const body = node.body
      ? this.fromStatement(node.body, generated.context)
      : undefined;

    const elseBody = node.elseBody
      ? this.fromStatement(node.elseBody, generated.context)
      : undefined;

    return [
      `(if ${this.fromComparison(generated, node.condition)[0]}`,
      `  (then`,
      ...(body?.code.map((line) => `    ${line}`) || []),
      `  )`,
      ...(elseBody ? [
        `  (else`,
        ...(elseBody?.code.map((line) => `    ${line}`) || []),
        `  )`,
      ] : []),
      `)`,
    ];
  }

  fromLoop(generated: GeneratedStatement, node: LoopBlockNode): string[] {
    const body = node.body
      ? this.fromStatement(node.body, generated.context)
      : undefined;

    if (node.condition instanceof LoopIfNode) {
      // while (condition) { body }
      return [
        `(block $break_${watName(node.name)}`,
        `  (loop $loop_${watName(node.name)}`,
        `    (br_if $break_${watName(node.name)} (i32.eqz ${this.fromComparison(generated, node.condition.condition)[0]}))`,
        ...(body?.code.map((line) => `    ${line}`) || []),
        `    (br $loop_${watName(node.name)})`,
        `  )`,
        `)`,
      ];
    }

    // do { body } while (condition)
    return [
      `(block $break_${watName(node.name)}`,
      `  (loop $loop_${watName(node.name)}`,
      ...(body?.code.map((line) => `    ${line}`) || []),
      `    ${node.condition?.condition ? `(br_if $loop_${watName(node.name)} ${this.fromComparison(generated, node.condition.condition)[0]})` : ''}`,
      `  )`,
      `)`,
    ];
  }

  fromTernaryExpression(
    generated: GeneratedStatement,
    node: TernaryExpressionNode,
  ): string[] {
    const comparisonCode = this.fromComparison(generated, node.condition);
    const trueCode = this.fromOperandExpression(generated, node.operand);
    const falseCode = this.fromExpression(generated, node.whenFalse);
    return [
      ...comparisonCode.slice(0, comparisonCode.length - 1),
      ...trueCode.slice(0, trueCode.length - 1),
      ...falseCode.slice(0, falseCode.length - 1),
      `(if (result i32) ${comparisonCode[comparisonCode.length - 1]} (then ${trueCode[trueCode.length - 1]}) (else ${falseCode[falseCode.length - 1]}))`,
    ];
  }

  /**
   * Check if a comparison operand has a signed coercion (e.g., :i8, :i16, :i32)
   * or is a local variable defined with signed: true.
   */
  private hasSignedCoercion(
    node: ComparisonNode | ExpressionNode | OperandNode,
    generated: GeneratedStatement,
  ): boolean {
    if (node instanceof OperandNode) {
      if (node.coercion?.startsWith('i')) return true;
      // Check if this is a local with signed: true in its definition
      if (node instanceof LocalOperandNode) {
        const localName = node.reference?.mapping?.identifier;
        if (localName) {
          // Look up the original local info to check signed flag
          for (const [key, info] of Object.entries(
            generated.context.locals || {},
          )) {
            if (
              generated.context.localMap?.[key]?.identifier === localName &&
              info.signed
            ) {
              return true;
            }
          }
        }
      }
    }
    if (node instanceof ExpressionNode) {
      if (node.operand instanceof OperandNode) {
        return this.hasSignedCoercion(node.operand, generated);
      }
    }
    return false;
  }

  fromComparisonEvaluation(
    generated: GeneratedStatement,
    node: ComparisonEvaluationNode,
  ): string[] {
    const left = this.fromComparisonOperand(generated, node.operand)[0];
    const right = this.fromComparisonOperand(generated, node.argument)[0];

    // Use signed comparison when either operand has a signed coercion (:i8, :i16, :i32)
    // or is a local defined with signed: true.
    // Otherwise use unsigned (matches JS behavior with Uint32Array)
    const signed =
      this.hasSignedCoercion(node.operand, generated) ||
      this.hasSignedCoercion(node.argument, generated);

    const opMap: Record<string, string> = signed
      ? {
          '==': 'i32.eq',
          '!=': 'i32.ne',
          '<': 'i32.lt_s',
          '>': 'i32.gt_s',
          '<=': 'i32.le_s',
          '>=': 'i32.ge_s',
        }
      : {
          '==': 'i32.eq',
          '!=': 'i32.ne',
          '<': 'i32.lt_u',
          '>': 'i32.gt_u',
          '<=': 'i32.le_u',
          '>=': 'i32.ge_u',
        };

    const op = opMap[node.operator];
    if (!op) {
      throw new Error(`Unknown comparison operator: ${node.operator}`);
    }

    return [`(${op} ${left} ${right})`];
  }

  fromUnaryExpression(
    generated: GeneratedStatement,
    node: UnaryExpressionNode,
  ): string[] {
    const operand = this.fromOperandExpression(generated, node.operand)[0];

    if (node.operator === '~') {
      // Bitwise NOT: xor with -1
      return [`(i32.xor ${operand} (i32.const -1))`];
    } else if (node.operator === '-') {
      // Negation: 0 - value
      return [`(i32.sub (i32.const 0) ${operand})`];
    }

    return [`(;; unknown unary ${node.operator} ;;) ${operand}`];
  }

  fromBinaryExpression(
    generated: GeneratedStatement,
    node: BinaryExpressionNode,
  ): string[] {
    const left = this.fromOperandExpression(generated, node.operand)[0];
    const right = this.fromOperandExpression(generated, node.argument)[0];

    if (node.operator === '//') {
      // Integer divide
      return [`(i32.div_s ${left} ${right})`];
    } else if (node.operator.startsWith('~>[')) {
      // Rotate right
      const width = parseInt(
        node.operator.substring(3, node.operator.length - 1),
      );
      if (width === 32) {
        return [`(i32.rotr ${left} ${right})`];
      }
      // For sub-32-bit rotations, use the formula:
      // (value >> amount) | ((value & ((1 << amount) - 1)) << (width - amount))
      // This is complex; we'll implement it as a series of ops
      return [
        `(i32.or (i32.shr_u ${left} (i32.rem_u ${right} (i32.const ${width}))) (i32.shl (i32.and ${left} (i32.sub (i32.shl (i32.const 1) (i32.rem_u ${right} (i32.const ${width}))) (i32.const 1))) (i32.sub (i32.const ${width}) (i32.rem_u ${right} (i32.const ${width})))))`,
      ];
    } else if (node.operator.startsWith('<~[')) {
      // Rotate left
      const width = parseInt(
        node.operator.substring(3, node.operator.length - 1),
      );
      if (width === 32) {
        return [`(i32.rotl ${left} ${right})`];
      }
      return [
        `(i32.or (i32.and (i32.shl ${left} (i32.rem_u ${right} (i32.const ${width}))) (i32.sub (i32.shl (i32.const 1) (i32.const ${width})) (i32.const 1))) (i32.shr_u ${left} (i32.sub (i32.const ${width}) (i32.rem_u ${right} (i32.const ${width})))))`,
      ];
    }

    const opMap: Record<string, string> = {
      '+': 'i32.add',
      '-': 'i32.sub',
      '*': 'i32.mul',
      '/': 'i32.div_s',
      '%': 'i32.rem_s',
      '&': 'i32.and',
      '|': 'i32.or',
      '^': 'i32.xor',
      '<<': 'i32.shl',
      '>>': 'i32.shr_s',
    };

    let op = opMap[node.operator];
    if (!op) {
      throw new Error(`Unknown binary operator: ${node.operator}`);
    }
    // Right shift: use signed or unsigned based on left operand's resolved type
    if (node.operator === '>>' && !(node.operand as Node).resolvedType?.signed) {
      op = 'i32.shr_u';
    }

    return [`(${op} ${left} ${right})`];
  }

  fromBinaryLogic(
    generated: GeneratedStatement,
    node: BinaryLogicNode,
  ): string[] {
    const left = this.fromComparison(
      generated,
      node.operand as ComparisonNode,
    )[0];
    const right = this.fromComparison(generated, node.argument)[0];

    if (node.operator === '&&') {
      return [`(i32.and ${left} ${right})`];
    } else if (node.operator === '||') {
      return [`(i32.or ${left} ${right})`];
    }

    return [`(;; unknown logic op ${node.operator} ;;)`];
  }

  // --- Decoder generation ---

  private craftInstruction(
    instruction: InstructionInfo,
    form: InstructionForm,
    index: number,
    _inputs: InputMap,
    variant: number,
    depth: number,
    indent: string,
    context: DecoderContext,
  ) {
    const target = this.target;
    const prefix = !!instruction.prefix;

    const ip =
      target.fetch?.effectiveRegister ||
      (Array.isArray(target.fetch?.register)
        ? target.fetch?.register?.[0]
        : target.fetch?.register);
    const instructionMemory = target.fetch?.memory;

    if (ip === undefined || instructionMemory === undefined) {
      throw new Error('Error: The target has no defined instruction pointer.');
    }

    const ipReference: RegisterReference = {
      type: 'register',
      identifier: ip,
      mapping: this.registerMap.registers[ip],
      size: this.registerMap.registers[ip].size,
    };

    const locals: LocalsInfo = {};
    for (const localInfo of instruction.locals || []) {
      locals[localInfo.identifier] = localInfo;
    }

    const generated: GeneratedStatement = {
      accesses: [],
      modifies: [],
      code: [],
      context: {
        mode: context.mode || this.target.modes?.[0]?.identifier || 'default',
        locals: {},
        localMap: { _ip: { identifier: '_ip' } },
      },
    };

    const { statement, localMap } =
      this.parsed.instructions[instruction.identifier][variant][context.mode]
        .operation;

    context.code.push(`${indent}(;; ${instruction.identifier}[${variant}] ;;)`);

    // Read the rest of the data for the instruction
    let bytesRead = 0;
    for (let i = 0; i < form.opcode.length; i++) {
      let matcher: string | number | OpcodeMatcher | undefined = form.opcode[i];
      const matcher_name =
        typeof matcher === 'string'
          ? matcher
          : typeof matcher === 'number'
            ? matcher.toString()
            : matcher.identifier;
      if (typeof matcher === 'string') {
        matcher = (target.operands || ([] as OpcodeMatcher[])).find(
          (operand) => operand.identifier === matcher_name,
        );
        if (matcher === undefined) {
          throw new Error(`Error: No operand found called ${matcher_name}`);
        }
        if (typeof matcher === 'string') {
          throw new Error(
            `Error: Operand ${matcher_name} improperly aliases another matcher '${matcher}'`,
          );
        }
      }

      if (matcher === undefined) continue;

      if (typeof matcher === 'number') {
        bytesRead++;
        continue;
      }

      // Read bytes we need for this matcher
      if (bytesRead > depth) {
        if ((matcher.size || 8) === 8) {
          const var_name = 'b' + bytesRead.toString();
          context.code.push(
            `${indent}(local.set $${var_name} (i32.load8_u (local.get $_ip)))`,
          );
          context.code.push(
            `${indent}(local.set $_ip (i32.add (local.get $_ip) (i32.const 1)))`,
          );
          if (!context.variables.includes(var_name)) {
            context.variables.push(var_name);
          }
        } else if (matcher.size === 16) {
          const var_name = 'b' + bytesRead.toString();
          context.code.push(
            `${indent}(local.set $${var_name} (i32.load16_u align=1 (local.get $_ip)))`,
          );
          context.code.push(
            `${indent}(local.set $_ip (i32.add (local.get $_ip) (i32.const 2)))`,
          );
          if (!context.variables.includes(var_name)) {
            context.variables.push(var_name);
          }
        } else if (matcher.size === 32) {
          const var_name = 'b' + bytesRead.toString();
          context.code.push(
            `${indent}(local.set $${var_name} (i32.load align=1 (local.get $_ip)))`,
          );
          context.code.push(
            `${indent}(local.set $_ip (i32.add (local.get $_ip) (i32.const 4)))`,
          );
          if (!context.variables.includes(var_name)) {
            context.variables.push(var_name);
          }
        }
      }
      bytesRead += (matcher.size || 8) / 8;

      for (const field of matcher.fields || [
        matcher as unknown as OpcodeMatcherField,
      ]) {
        if (typeof field === 'string') continue;
        if (field.match !== undefined) continue;

        const var_name = field.identifier;
        locals[var_name] = {
          identifier: var_name,
          size: matcher.size,
          signed: matcher.signed,
        };

        const variableCount = Object.keys(localMap).length;
        const allocated_name =
          var_name in localMap
            ? localMap[var_name].identifier
            : `v_${variableCount}`;
        if (!(var_name in localMap)) {
          localMap[var_name] = { identifier: allocated_name };
        }

        let readExpr = `(local.get $b${bytesRead - (matcher.size || 8) / 8})`;

        if (field.offset) {
          readExpr = `(i32.shr_u ${readExpr} (i32.const ${field.offset}))`;
        }

        if (typeof field.size === 'number') {
          const mask = Math.pow(2, field.size) - 1;
          readExpr = `(i32.and ${readExpr} (i32.const 0x${mask.toString(16)}))`;
        }

        if (matcher.signed) {
          readExpr = this.signExtend(readExpr, matcher.size || 8);
        }

        context.code.push(
          `${indent}(local.set $${allocated_name} ${readExpr})`,
        );

        if (!context.variables.includes(allocated_name)) {
          context.variables.push(allocated_name);
        }
      }
    }

    // Advance instruction pointer
    if (target.fetch?.advancePointer) {
      const ipRead = this.readRegister(generated, ipReference)[0];
      context.code.push(
        `${indent}${this.writeRegister(generated, ipReference, `(i32.add ${ipRead} (i32.const 0x${bytesRead.toString(16)}))`)[0]}`,
      );
      generated.context.ipAdvance = bytesRead;
    }

    // Handle prefix finalize
    if (
      prefix &&
      ((form as InstructionFormFlat).finalize ||
        (form as InstructionFormModes).modes?.[context.mode]?.finalize)
    ) {
      context.code.push(
        `${indent}(local.set $_finalize_id (i32.const 0x${context.prefixCount.toString(16)}))`,
      );
      context.code.push(`${indent}(local.set $_has_finalize (i32.const 1))`);
      context.prefixMap.push({ instruction, variant });
      context.prefixCount++;
    }

    // Transpile the instruction body
    if (statement) {
      const { code } = this.fromStatement(statement, {
        mode: context.mode || this.target.modes?.[0]?.identifier || 'default',
        locals,
        localMap,
        ipAdvance: generated.context.ipAdvance,
      });
      for (const line of code) {
        context.code.push(indent + line);
      }
      for (const localInfo of Object.values(localMap)) {
        const var_name = localInfo.identifier;
        if (!context.variables.includes(var_name)) {
          context.variables.push(var_name);
        }
      }
    }
  }

  private craftDecoderState(
    decoder: DecoderMap,
    depth: number,
    indent: string,
    context: DecoderContext,
    prefix: boolean = false,
  ) {
    const target = this.target;
    const startIndex = context.code.length;

    const ip =
      target.fetch?.effectiveRegister ||
      (Array.isArray(target.fetch?.register)
        ? target.fetch?.register?.[0]
        : target.fetch?.register);
    const instructionMemory = target.fetch?.memory;

    if (ip === undefined || instructionMemory === undefined) {
      throw new Error('Error: The target has no defined instruction pointer.');
    }

    if (depth === 0 && !prefix) {
      const { start } = this.memoryMap[instructionMemory];
      const ipReference: RegisterReference = {
        type: 'register',
        identifier: ip,
        mapping: this.registerMap.registers[ip],
        size: this.registerMap.registers[ip].size,
      };
      const generated: GeneratedStatement = {
        accesses: [],
        modifies: [],
        code: [],
        context: {
          mode: this.target.modes?.[0]?.identifier || 'default',
          locals: {},
          localMap: { _ip: { identifier: '_ip' } },
        },
      };

      // Placeholder for local declarations (will be filled in later)
      context.code.push('');

      // Load IP into local
      context.code.push(
        `${indent}(local.set $_ip (i32.add ${this.readRegister(generated, ipReference)[0]} (i32.const 0x${(start || 0).toString(16)})))`,
      );
      context.code.push(`${indent}(local.set $_has_finalize (i32.const 0))`);

      // Save IP at start of instruction (before prefixes) for fault rollback
      if (!context.variables.includes('_ip_save')) {
        context.variables.push('_ip_save');
      }
      const ipForSave =
        this.target.fetch?.effectiveRegister ||
        (Array.isArray(this.target.fetch?.register)
          ? this.target.fetch?.register?.[0]
          : this.target.fetch?.register);
      if (ipForSave && this.registerMap.registers[ipForSave]) {
        const ipRefSave: RegisterReference = {
          type: 'register',
          identifier: ipForSave,
          mapping: this.registerMap.registers[ipForSave],
          size: this.registerMap.registers[ipForSave].size,
        };
        context.code.push(
          `${indent}(local.set $_ip_save ${this.readRegister(generated, ipRefSave)[0]})`,
        );
      }
      // Prefix loop
      context.code.push(`${indent}(block $done`);
      context.code.push(`${indent}  (loop $outer`);
      indent += '    ';
    }

    const byteName = 'b' + depth;
    if (!context.variables.includes(byteName)) {
      context.variables.push(byteName);
    }

    if (!prefix) {
      // Fetch byte
      context.code.push(
        `${indent}(local.set $${byteName} (i32.load8_u (local.get $_ip)))`,
      );
      context.code.push(
        `${indent}(local.set $_ip (i32.add (local.get $_ip) (i32.const 1)))`,
      );
    }

    // Check if we need a dispatch wrapper block (when both exact and partial exist)
    const hasExact = !!decoder.exact;
    const partials = decoder.partial || [];
    const hasPartials = partials.length > 0;
    let dispatchDoneLabel: string | undefined;

    if (hasExact && hasPartials) {
      const dispatchId = context.labelCounter++;
      dispatchDoneLabel = `$dispatch_done_${dispatchId}`;
      context.code.push(`${indent}(block ${dispatchDoneLabel}`);
    }

    // Handle exact matches via br_table
    if (decoder.exact) {
      // Count how many valid entries we have
      const validEntries: { index: number; entry: DecoderMap }[] = [];
      for (let i = 0; i < decoder.exact.length; i++) {
        if (decoder.exact[i]) {
          validEntries.push({ index: i, entry: decoder.exact[i] });
        }
      }

      const switchId = context.labelCounter++;
      const doneLabel = `$switch_done_${switchId}`;
      // When there are partial matches, exact match cases break to the outer
      // dispatch block to skip past partials. Default case breaks to switch_done
      // to fall through to partial matching.
      const caseDoneLabel = dispatchDoneLabel || doneLabel;

      // Build the br_table target array (256 entries for a byte)
      const tableSize = 256;
      const blockLabels: string[] = []; // one per valid case
      const blockMap = new Map<number, number>(); // opcode -> block index

      for (let vi = 0; vi < validEntries.length; vi++) {
        const label = `$case_${switchId}_${validEntries[vi].index}`;
        blockLabels.push(label);
        blockMap.set(validEntries[vi].index, vi);
      }

      const defaultLabel = `$default_${switchId}`;

      // Build target array for br_table
      const targets: string[] = [];
      for (let i = 0; i < tableSize; i++) {
        if (blockMap.has(i)) {
          targets.push(blockLabels[blockMap.get(i)!]);
        } else {
          targets.push(defaultLabel);
        }
      }

      // Emit nested blocks (outermost = first to execute after branch)
      // br_table branches OUT of a block, so:
      // (block $case_N  ;; innermost case exits here
      //   (block $case_0
      //     (block $default
      //       (br_table ...)
      //     )
      //     ;; default code here
      //     (br $switch_done)
      //   )
      //   ;; case_0 code here
      //   (br $switch_done)
      // )
      // ;; case_N code here

      context.code.push(`${indent}(block ${doneLabel}`);

      // Open blocks for each case (in reverse order since innermost = first case)
      for (let vi = validEntries.length - 1; vi >= 0; vi--) {
        context.code.push(`${indent}  (block ${blockLabels[vi]}`);
      }

      // Default block
      context.code.push(`${indent}    (block ${defaultLabel}`);

      // The br_table itself
      context.code.push(
        `${indent}      (br_table ${targets.join(' ')} ${defaultLabel} (local.get $${byteName}))`,
      );

      // Close default block
      context.code.push(`${indent}    ) ;; ${defaultLabel}`);
      // Default case: break to done
      context.code.push(`${indent}    (br ${doneLabel})`);

      // Now emit each case's code
      for (let vi = 0; vi < validEntries.length; vi++) {
        const { index: opcodeVal, entry: matcher } = validEntries[vi];
        context.code.push(
          `${indent}  ) ;; ${blockLabels[vi]} (0x${opcodeVal.toString(16)})`,
        );

        if (
          matcher.instruction &&
          matcher.form &&
          matcher.index !== undefined &&
          matcher.inputs !== undefined &&
          matcher.variant !== undefined
        ) {
          this.craftInstruction(
            matcher.instruction,
            matcher.form,
            matcher.index,
            matcher.inputs,
            matcher.variant,
            depth,
            indent + '  ',
            context,
          );
          if (matcher.instruction.prefix) {
            context.code.push(`${indent}  (br $outer)`);
          } else {
            context.code.push(`${indent}  (br ${caseDoneLabel})`);
          }
        } else if (matcher.exact || matcher.partial) {
          this.craftDecoderState(
            matcher,
            depth + 1,
            indent + '  ',
            context,
            prefix,
          );
          context.code.push(`${indent}  (br ${caseDoneLabel})`);
        } else {
          context.code.push(`${indent}  (br ${caseDoneLabel})`);
        }
      }

      // Close the done block
      context.code.push(`${indent}) ;; ${doneLabel}`);
    }

    // Handle wildcard
    if (decoder.wildcard) {
      this.craftDecoderState(
        decoder.wildcard.map,
        depth + 1,
        indent,
        context,
        prefix,
      );
    }

    // Handle partial matches (bit-masked)
    // Wrap in a block so that once one partial matches, the rest are skipped
    if (partials.length > 0) {
      const partialBlockId = context.labelCounter++;
      const partialDoneLabel = `$partial_done_${partialBlockId}`;
      context.code.push(`${indent}(block ${partialDoneLabel}`);

      for (const { mask, and, map } of partials) {
        const condExpr = `(i32.eq (i32.and (local.get $${byteName}) (i32.const 0x${mask.toString(16)})) (i32.const 0x${and.toString(16)}))`;

        context.code.push(`${indent}  (if ${condExpr}`);
        context.code.push(`${indent}    (then`);

        if (
          map.instruction &&
          map.form &&
          map.index !== undefined &&
          map.inputs !== undefined &&
          map.variant !== undefined
        ) {
          this.craftInstruction(
            map.instruction,
            map.form,
            map.index,
            map.inputs,
            map.variant,
            depth,
            indent + '      ',
            context,
          );
          if (map.instruction.prefix) {
            context.code.push(`${indent}      (br $outer)`);
          }
        } else {
          this.craftDecoderState(
            map,
            depth + 1,
            indent + '      ',
            context,
            prefix,
          );
        }

        // Break out of partial block after first match
        context.code.push(`${indent}      (br ${partialDoneLabel})`);
        context.code.push(`${indent}    )`);
        context.code.push(`${indent}  )`);
      }

      context.code.push(`${indent}) ;; ${partialDoneLabel}`);
    }

    // Close outer dispatch block (wraps exact + partial to prevent double-firing)
    if (dispatchDoneLabel) {
      context.code.push(`${indent}) ;; ${dispatchDoneLabel}`);
    }

    if (depth === 0 && !prefix) {
      // End the prefix loop
      indent = indent.substring(0, indent.length - 4);
      context.code.push(`${indent}  ) ;; end loop $outer`);
      context.code.push(`${indent}) ;; end block $done`);

      // Finalizers
      if (context.prefixMap.length > 0) {
        context.code.push(`${indent}(if (local.get $_has_finalize)`);
        context.code.push(`${indent}  (then`);
        // Switch on finalize ID
        const finSwitchId = context.labelCounter++;
        const finDoneLabel = `$fin_done_${finSwitchId}`;

        context.code.push(`${indent}    (block ${finDoneLabel}`);
        const finLabels = context.prefixMap.map(
          (_, idx) => `$fin_${finSwitchId}_${idx}`,
        );

        for (let i = finLabels.length - 1; i >= 0; i--) {
          context.code.push(`${indent}      (block ${finLabels[i]}`);
        }

        const finTargets = finLabels.join(' ');
        context.code.push(
          `${indent}        (br_table ${finTargets} ${finDoneLabel} (local.get $_finalize_id))`,
        );

        for (let i = 0; i < finLabels.length; i++) {
          context.code.push(`${indent}      ) ;; ${finLabels[i]}`);
          const { instruction, variant } = context.prefixMap[i];
          const node =
            this.parsed.instructions[instruction.identifier][variant][
              context.mode
            ].finalize?.statement;
          if (node) {
            const { code } = this.fromStatement(node);
            for (const line of code) {
              context.code.push(`${indent}      ${line}`);
            }
          }
          context.code.push(`${indent}      (br ${finDoneLabel})`);
        }

        context.code.push(`${indent}    ) ;; ${finDoneLabel}`);
        context.code.push(`${indent}  )`);
        context.code.push(`${indent})`);
      }

      // Write in local declarations at the placeholder
      let declCode = '';
      // Always include _ip, _has_finalize, _finalize_id
      declCode +=
        '    (local $_ip i32) (local $_has_finalize i32) (local $_finalize_id i32)';
      context.variables.sort().forEach((name) => {
        declCode += ` (local $${name} i32)`;
      });
      context.code[startIndex] = declCode;
    }
  }

  buildDecoder(mode: string): string[] {
    const decoder = this.decoderMap;
    const context: DecoderContext = {
      mode,
      code: [],
      variables: [],
      bytesCount: 0,
      prefixCount: 0,
      prefixMap: [],
      labelCounter: 0,
    };

    if (!decoder) {
      return [];
    }

    const modeInfo = (this.target.modes || []).find(
      (info) => info.identifier === mode,
    );

    context.code.push(
      `  ;; Decode and execute one instruction in '${mode}' mode`,
    );
    context.code.push(
      `  (func $decode_${mode} (export "decode_${mode}") (result i32)`,
    );

    if (modeInfo?.decode) {
      this.craftDecoderState(decoder, 0, '    ', context);
    }

    // Return cycles (for now, always 0 — TODO: track per-instruction)
    context.code.push('    (i32.const 0)');
    context.code.push('  )');
    context.code.push('');

    // run(maxCycles) function
    context.code.push(
      `  ;; Execute instructions until cycle budget exhausted in '${mode}' mode`,
    );
    context.code.push(
      `  (func $run_${mode} (export "run_${mode}") (param $max_cycles i32) (result i32)`,
    );
    context.code.push('    (local $total i32)');
    context.code.push('    (block $exit');
    context.code.push('      (loop $loop');
    context.code.push(
      `        (local.set $total (i32.add (local.get $total) (call $decode_${mode})))`,
    );
    context.code.push(
      '        (br_if $exit (i32.ge_u (local.get $total) (local.get $max_cycles)))',
    );
    context.code.push('        (br $loop)');
    context.code.push('      )');
    context.code.push('    )');
    context.code.push('    (local.get $total)');
    context.code.push('  )');
    context.code.push('');

    return context.code;
  }
}

export default WebAssemblyBackend;
