export const interrupts = {
  handler: {
    locals: [
      {
        identifier: 'NEW_CS',
        name: 'Target interrupt vector CS',
        size: 16,
      },
      {
        identifier: 'NEW_IP',
        name: 'Target interrupt vector IP',
        size: 16,
      },
      {
        identifier: 'stack_address',
        name: 'Effective Stack Address',
        size: 32,
      },
      {
        identifier: 'offset',
        name: 'Effective Offset',
        size: 32,
      },
      {
        identifier: 'tmp',
        name: 'Temporary value',
        size: 16,
      },
      {
        identifier: 'index',
        name: 'Descriptor table entry index',
        size: 16,
      },
      {
        identifier: 'desc_type',
        name: 'Descriptor type field',
        size: 8,
      },
      {
        identifier: 'desc_s',
        name: 'Descriptor S bit',
        size: 8,
      },
      {
        identifier: 'desc_dpl',
        name: 'Descriptor privilege level',
        size: 8,
      },
      {
        identifier: 'desc_p',
        name: 'Descriptor present bit',
        size: 8,
      },
      {
        identifier: 'desc_limit',
        name: 'Descriptor limit',
        size: 16,
      },
      {
        identifier: 'desc_base',
        name: 'Descriptor base',
        size: 32,
      },
      {
        identifier: 'new_cpl',
        name: 'New privilege level',
        size: 8,
      },
      {
        identifier: 'new_sp',
        name: 'New stack pointer from TSS',
        size: 16,
      },
      {
        identifier: 'new_ss',
        name: 'New stack segment from TSS',
        size: 16,
      },
      {
        identifier: 'old_cs',
        name: 'Saved CS before switch',
        size: 16,
      },
      {
        identifier: 'old_ss',
        name: 'Saved SS before switch',
        size: 16,
      },
      {
        identifier: 'old_sp',
        name: 'Saved SP before switch',
        size: 16,
      },
      {
        identifier: 'gate_type',
        name: 'IDT gate type field',
        size: 8,
      },
      {
        identifier: 'saved_error_code',
        name: 'Saved error code from faulting instruction',
        size: 16,
      },
      // Task switch support (for IDT task gates)
      {
        identifier: 'tss_sel',
        name: 'Target TSS selector',
        size: 16,
      },
      {
        identifier: 'tss_index',
        name: 'Target TSS GDT index',
        size: 16,
      },
      {
        identifier: 'old_tss_index',
        name: 'Old TSS GDT index',
        size: 16,
      },
      {
        identifier: 'old_tr_sel',
        name: 'Old TR selector (before switch)',
        size: 16,
      },
      {
        identifier: 'task_nesting',
        name: 'Task nesting flag (1=CALL/INT, 0=JMP)',
        size: 8,
      },
      {
        identifier: 'ldtr_sel',
        name: 'LDTR selector from new TSS',
        size: 16,
      },
      {
        identifier: 'ldtr_index',
        name: 'LDTR GDT index',
        size: 16,
      },
    ],
    modes: {
      real: {
        operation: [
          ';; triple fault: halt the machine',
          'if EXCEPTION_DEPTH > 1',
          ['HALTED = 1', 'HALTED_CS = CS', 'HALTED_IP = IP'],
          'end if',
          ';; double fault: escalate to vector 8',
          'if EXCEPTION_DEPTH == 1',
          ['EXCEPTION_DEPTH = 2', 'vector = 8'],
          'end if',
          ';; normal fault: mark as delivering',
          'if EXCEPTION_DEPTH == 0',
          ['EXCEPTION_DEPTH = 1'],
          'end if',
          ';; dispatch if not halted',
          'if HALTED == 0',
          [
            ';; check IF flag for maskable interrupts',
            ';; check to see if the interrupt handler exists',
            'NEW_CS = RAM.IVT.vectors[vector].segment',
            'NEW_IP = RAM.IVT.vectors[vector].offset',
            ';; push CS / IP / FLAGS on to the stack',
            'tmp = SP - 6',
            'offset = tmp',
            'stack_address = SS_BASE + offset',
            '#GP if offset == 0xffff',
            '#GP if (offset + 2) == 0xffff',
            '#GP if (offset + 4) == 0xffff',
            '${RESOLVE_FLAGS}',
            'RAM:u16[stack_address] = IP',
            'RAM:u16[stack_address + 2] = CS',
            'RAM:u16[stack_address + 4] = FLAGS',
            'SP = tmp',
            ';; successfully dispatched, reset depth',
            'EXCEPTION_DEPTH = 0',
            ';; jump to the interrupt handler',
            'CS = NEW_CS',
            'IP = NEW_IP',
          ],
          'end if',
        ],
      },
      protected: {
        operation: [
          ';; triple fault: halt the machine',
          'if EXCEPTION_DEPTH > 1',
          ['HALTED = 1', 'HALTED_CS = CS', 'HALTED_IP = IP'],
          'end if',
          ';; double fault: escalate to vector 8',
          'if EXCEPTION_DEPTH == 1',
          ['EXCEPTION_DEPTH = 2', 'vector = 8'],
          'end if',
          ';; normal fault: mark as delivering',
          'if EXCEPTION_DEPTH == 0',
          ['EXCEPTION_DEPTH = 1'],
          'end if',
          ';; dispatch if not halted',
          'if HALTED == 0',
          [
            ';; capture and clear software INT flag',
            'tmp = SOFTWARE_INT',
            'SOFTWARE_INT = 0',
            ';; IDT bounds check',
            '#GP if (vector * 8 + 7) > IDTR.limit',
            ';; gate must be present (P is at same offset in both IGD and TGD)',
            '#NP if RAM.IDT.gates[vector].IGD.P != 1',
            ';; software INT: gate DPL must be >= CPL (DPL is at same offset in both)',
            'if tmp == 1',
            [
              'ERROR_CODE = vector * 8 + 2',
              '#GP if RAM.IDT.gates[vector].IGD.DPL < (CS.RPL)',
            ],
            'end if',
            ';; detect gate type (bits 41-43 of the descriptor)',
            'gate_type = RAM.IDT.gates[vector].IGD.gate_type',
            ';; save error code before gate validation clobbers ERROR_CODE',
            'saved_error_code = ERROR_CODE',

            ';; === IDT TASK GATE (gate_type=010) ===',
            'if gate_type == 0b010',
            [
              ';; read TSS selector from task gate',
              'tss_sel = RAM.IDT.gates[vector].TGD.selector',
              ';; validate TSS selector',
              'ERROR_CODE = tss_sel',
              ';; must be in GDT (TI bit = 0)',
              '#GP if (tss_sel & 0x0004) != 0',
              'tss_index = tss_sel >> 3',
              '#GP if tss_index == 0',
              '#GP if (tss_index * 8) > GDTR.limit',
              ';; must be available TSS (S=0, A=1, type=000)',
              '#GP if RAM.GDT.gates[tss_index].SD.S != 0',
              '#GP if RAM.GDT.gates[tss_index].SD.A != 1',
              '#GP if RAM.GDT.gates[tss_index].SD.type != 0b000',
              ';; must be present',
              '#NP if RAM.GDT.gates[tss_index].SD.P != 1',
              ';; load TSS descriptor fields for TASK_SWITCH',
              'desc_base = RAM.GDT.gates[tss_index].SD.base',
              'desc_limit = RAM.GDT.gates[tss_index].SD.limit',
              ';; nested task switch (interrupts are always nested)',
              'task_nesting = 1',
              '${TASK_SWITCH}',
              ';; push error code for exceptions that require it (on new task stack)',
              'if vector == 8 || vector == 10 || vector == 11 || vector == 12 || vector == 13',
              [
                'tmp = SP - 2',
                'offset = tmp',
                'stack_address = SS_BASE + offset',
                '#SS if offset < SS_LIMIT_MIN',
                '#SS if (offset + 1) > SS_LIMIT_MAX',
                'RAM:u16[stack_address] = saved_error_code',
                'SP = tmp',
                'ERROR_CODE = 0',
              ],
              'end if',
              ';; successfully dispatched, reset depth',
              'EXCEPTION_DEPTH = 0',
            ],
            'end if',

            ';; === INTERRUPT/TRAP GATE (gate_type=011) ===',
            'if gate_type == 0b011',
            [
              ';; read gate descriptor fields',
              'NEW_CS = RAM.IDT.gates[vector].IGD.segment',
              'NEW_IP = RAM.IDT.gates[vector].IGD.offset',
              ';; validate target CS selector (may be in GDT or LDT)',
              'ERROR_CODE = NEW_CS',
              'tmp = NEW_CS',
              'index = tmp >> 3',
              '#GP if index == 0',
              '${DESCRIPTOR_BOUNDS_CHECK}',
              '${LOAD_DESCRIPTOR_FIELDS}',
              '#GP if desc_s != 1',
              '#GP if (desc_type & 0b100) != 0b100',
              '#NP if desc_p != 1',
              ';; determine new privilege level',
              'new_cpl = desc_dpl',
              ';; save old state before any modifications',
              'old_cs = CS',
              'old_ss = SS',
              'old_sp = SP',
              ';; INTERRUPT TO INNER PRIVILEGE',
              ';; non-conforming code with DPL < CPL',
              'if (desc_type & 0b010) != 0b010 && new_cpl < (CS.RPL)',
              [
                ';; read new SS:SP from TSS for target privilege level',
                'new_ss = SS',
                'new_sp = SP',
                'if new_cpl == 0',
                ['new_sp = RAM.TSS.SP0', 'new_ss = RAM.TSS.SS0'],
                'end if',
                'if new_cpl == 1',
                ['new_sp = RAM.TSS.SP1', 'new_ss = RAM.TSS.SS1'],
                'end if',
                'if new_cpl == 2',
                ['new_sp = RAM.TSS.SP2', 'new_ss = RAM.TSS.SS2'],
                'end if',
                ';; set RPL of new CS to new CPL and load CS',
                'NEW_CS = (NEW_CS & 0xfffc) | new_cpl',
                'CS = NEW_CS',
                ';; switch to new stack (SS set validates against new CPL)',
                'SS = new_ss',
                'SP = new_sp',
                ';; push old SS:SP, FLAGS, CS:IP on new stack (10 bytes)',
                '${RESOLVE_FLAGS}',
                'tmp = SP - 10',
                'offset = tmp',
                'stack_address = SS_BASE + offset',
                '#SS if offset < SS_LIMIT_MIN',
                '#SS if (offset + 9) > SS_LIMIT_MAX',
                'RAM:u16[stack_address] = IP',
                'RAM:u16[stack_address + 2] = old_cs',
                'RAM:u16[stack_address + 4] = FLAGS',
                'RAM:u16[stack_address + 6] = old_sp',
                'RAM:u16[stack_address + 8] = old_ss',
                'SP = tmp',
              ],
              'end if',
              ';; INTERRUPT TO SAME PRIVILEGE',
              ';; conforming code, or DPL == CPL',
              'if (desc_type & 0b010) == 0b010 || new_cpl == (old_cs & 0x0003)',
              [
                ';; push FLAGS, CS:IP on current stack (6 bytes)',
                '${RESOLVE_FLAGS}',
                'tmp = SP - 6',
                'offset = tmp',
                'stack_address = SS_BASE + offset',
                '#SS if offset < SS_LIMIT_MIN',
                '#SS if (offset + 5) > SS_LIMIT_MAX',
                'RAM:u16[stack_address] = IP',
                'RAM:u16[stack_address + 2] = CS',
                'RAM:u16[stack_address + 4] = FLAGS',
                'SP = tmp',
                ';; set RPL of new CS to CPL and load CS',
                'NEW_CS = (NEW_CS & 0xfffc) | (CS.RPL)',
                'CS = NEW_CS',
              ],
              'end if',
              ';; push error code for exceptions that require it',
              'if vector == 8 || vector == 10 || vector == 11 || vector == 12 || vector == 13',
              [
                'tmp = SP - 2',
                'offset = tmp',
                'stack_address = SS_BASE + offset',
                '#SS if offset < SS_LIMIT_MIN',
                '#SS if (offset + 1) > SS_LIMIT_MAX',
                'RAM:u16[stack_address] = saved_error_code',
                'SP = tmp',
                'ERROR_CODE = 0',
              ],
              'end if',
              ';; successfully dispatched, reset depth',
              'EXCEPTION_DEPTH = 0',
              ';; load new IP',
              'IP = NEW_IP',
              ';; interrupt gates (T=0) clear IF ... trap gates (T=1) leave IF',
              'if RAM.IDT.gates[vector].IGD.T == 0',
              ['IF = 0'],
              'end if',
              ';; clear TF and NT',
              'TF = 0',
              'NT = 0',
            ],
            'end if',
          ],
          'end if',
        ],
      },
    },
  },
  vectors: [
    {
      identifier: 'DE',
      name: 'Divide Error',
      index: 0,
    },
    {
      identifier: 'DB',
      name: 'Single Step Interrupt',
      index: 1,
    },
    {
      identifier: 'NMI',
      name: 'Non-maskable Interrupt',
      index: 2,
    },
    {
      identifier: 'BP',
      name: 'Breakpoint',
      index: 3,
    },
    {
      identifier: 'OF',
      name: 'Overflow',
      index: 4,
    },
    {
      identifier: 'BR',
      name: 'Bound Range Exceeded',
      index: 5,
    },
    {
      identifier: 'UD',
      name: 'Invalid Opcode',
      index: 6,
    },
    {
      identifier: 'NM',
      name: 'Device Not Available',
      index: 7,
    },
    {
      identifier: 'DF',
      name: 'Double Fault',
      index: 8,
    },
    {
      identifier: 'TS',
      name: 'Invalid Task State Segment',
      index: 10,
    },
    {
      identifier: 'NP',
      name: 'Segment Not Present',
      index: 11,
    },
    {
      identifier: 'SS',
      name: 'Stack Segment Fault',
      index: 12,
    },
    {
      identifier: 'GP',
      name: 'General Protection Fault',
      index: 13,
    },
    {
      identifier: 'MF',
      name: 'x87 Floating-Point Exception',
      index: 16,
    },
  ],
};

export default interrupts;
